<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Filter userProfiles</name>
   <tag></tag>
   <elementGuidId>d9a4c305-1058-4d95-b8e5-f447f52de887</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;filters\&quot;: [\r\n        {\r\n            \&quot;columnName\&quot;: \&quot;name\&quot;,\r\n            \&quot;columnValue\&quot;: \&quot;Media Outlet\&quot;,\r\n            \&quot;operator\&quot;: \&quot;equals\&quot;\r\n        }\r\n    ],\r\n    \&quot;pageNo\&quot;: 0,\r\n    \&quot;pageLength\&quot;: 10,\r\n    \&quot;sorting\&quot;: [\r\n        {\r\n            \&quot;sortName\&quot;: \&quot;id\&quot;,\r\n            \&quot;sortType\&quot;: \&quot;DESC\&quot;,\r\n            \&quot;sortColumnType\&quot;: \&quot;string\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>46b7052a-b12e-424c-aeac-120a760de8ef</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>e051210a-5add-405e-b0d5-eaf5584ffff6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTcwMTI3MjYsImlhdCI6MTY5NzAwOTEyNiwiYXV0aF90aW1lIjoxNjk3MDA5MTI1LCJqdGkiOiJhYjA1YWQ4Yi0wZDBjLTQ2ZTgtODljYy01ZGYzOGI2MjZmZTUiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjdiMmUwYWZlLThmZGQtNDM5ZS04ZTBiLTdmYjk1ZDk2N2EwNSIsInNlc3Npb25fc3RhdGUiOiI0ZDUxYTkzNy1kNmNkLTRhNTItYmZhOC01Mzk4OTc3YmZjNjEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX1VQX0RfTyIsIkNfVENfRV9PIiwiQ19DTF9FTVlfTyIsIkNfQ1JRX0VfTyIsIkNfVF9WX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX01FX1VOQl9PIiwiQ19NRV9EU19PIiwiZGVmYXVsdC1yb2xlcy1jdXN0X2VzcG9ydHMuY29tIiwiQ19BTF9FWFBfTyIsIkNfQ0xfVl9PIiwiQ19UX0FfTyIsIkNfUl9WQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRUFMX08iLCJDX0NMX0VYUF9PIiwiQ19UX0VBTF9PIiwiQ19VUF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVVBfQV9PIiwiQ19DTF9BU19PIiwiQ19VX0VfTyIsIkNfT19WX08iLCJDX1JTX0VfTyIsIkNfVV9VQkxfTyIsIkVTUE9SVCIsIkNfTUVfRVhQX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9FWFBfTyIsIkNfQ0xfQkxfTyIsIkNfTUVfRUFQX08iLCJDX0NMX0NBTF9PIiwiQ19VX1ZfTyIsIkNfTUVfTUFfTyIsIkNfTUVfVkFMX08iLCJDX0NMX0RTX08iLCJDX05SX0VfTyIsIkNfVF9BUkxfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiI0ZDUxYTkzNy1kNmNkLTRhNTItYmZhOC01Mzk4OTc3YmZjNjEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJzdXBlciBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTQyNTQyMzIiLCJnaXZlbl9uYW1lIjoic3VwZXIgYWRtaW4iLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZmFtaWx5X25hbWUiOiIiLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYWRtaW5Ac2F1ZGllc3BvcnRzLnNhIiwiY2lkIjoiMV9TVENTX0NVU1QifQ.dMevOwNVzkEjLPtsYFhGTxqGl29_Ju8v7lUA-qi7O4yollYyNdPUumfxoNRvRf_0VrPzPPqQ2ubfZm4YG7qUBVJn2h4XrLVNafS0MxWH5IGK0-UP-7vPiAio3f_HcqJvbOuFJM-m6e24r7OVUhHRoMcPyFyE66jTV3cD7qRDNUO2AgRraIGkQMZsiNIKkUUZUFhgAPafkeAflJFvpW-jxPLaCa7cWAKPz-o3BAHJZoDhX6El_AIYQEMl7d9NRtBTGAU-hjiYs1afN3Sj_U54PnFneL1aR3eqWeQAyVGj7lho3sFOzB4XfdIu7bwjYFCcOW-VA5KQ_MC0Dev6iyQYaw</value>
      <webElementGuid>6769966a-d60e-440e-aa79-aeae129ffd16</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>924149e3-93f5-45fb-8f45-f37a0864dfbe</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>22770e53-a22f-4d55-a82c-20ea4eb3350a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>4d19c99d-ab96-4045-94eb-858bb2a59758</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>de5160d6-c0d4-47fb-a722-83826c7d528d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/account/profiles/view/2441ea00-05a9-49fd-aa0f-68ea4dc838e2</value>
      <webElementGuid>118d8066-a1ab-44b3-9e7c-a45f1dda32d8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>fc1ea116-6633-4380-a082-eec9e3c98a9f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>dba3d2bd-1938-4651-90e3-fa4d753baf6e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>1fb6ec2b-1552-4cc0-8001-87ca14567dce</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</value>
      <webElementGuid>5dd6bb3b-a3d5-4007-8c98-9c8c9af68d2c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;117&quot;, &quot;Not;A=Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;117&quot;</value>
      <webElementGuid>465fc5d4-6024-4cfd-8952-5bf9ac716b1b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>4a11724d-3791-4f60-ae99-7b8aef15a822</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>8ffc1c10-d7f3-47eb-b25a-9062bec1335a</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/uaa/profile/filter</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
