<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update profile</name>
   <tag></tag>
   <elementGuidId>0a68b751-d2e7-4884-ba39-121c8818ffca</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\&quot;name\&quot;:\&quot;Content Creator\&quot;,\&quot;nameAr\&quot;:\&quot;صانع محتوى\&quot;,\&quot;levelId\&quot;:\&quot;f94e0251-62d1-4aa4-bc55-c4334d3fa114\&quot;,\&quot;signUp\&quot;:true,\&quot;authorities\&quot;:[\&quot;C_T_A_O\&quot;,\&quot;C_T_E_O\&quot;,\&quot;C_T_UAR_O\&quot;,\&quot;C_T_AR_O\&quot;,\&quot;C_T_MTA_O\&quot;,\&quot;C_T_DS_O\&quot;,\&quot;C_CL_DS_O\&quot;,\&quot;C_CL_VMY_O\&quot;,\&quot;C_ME_DS_O\&quot;,\&quot;C_ME_VAL_O\&quot;],\&quot;id\&quot;:\&quot;4e6cdc1e-3bee-4946-98c4-14a99d3999bd\&quot;,\&quot;isInvitationsEnabled\&quot;:true}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>6c6a02c1-1594-4dc2-bbc0-fc7c5b6f7e28</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>d153c604-442d-475f-82fd-37997d2459e3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTY5NDE5MjgsImlhdCI6MTY5NjkzODMyOCwiYXV0aF90aW1lIjoxNjk2OTM4MzI3LCJqdGkiOiIyYjIzNDQ0My05NzkyLTQ0MTgtODYzOC0xYzlmMGE0NjY2ZTciLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjE3ODgxYTdhLTQ4OWItNGJmMC1hMGVhLTExZTEwY2EyYWQ4ZiIsInNlc3Npb25fc3RhdGUiOiI1NDY5NWYwMi0xZTlhLTQ5ODUtYWU0MS1lNjk0Y2UwYjZmODAiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX1VQX0RfTyIsIkNfVENfRV9PIiwiQ19DTF9FTVlfTyIsIkNfQ1JRX0VfTyIsIkNfVF9WX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX01FX1VOQl9PIiwiQ19NRV9EU19PIiwiZGVmYXVsdC1yb2xlcy1jdXN0X2VzcG9ydHMuY29tIiwiQ19BTF9FWFBfTyIsIkNfQ0xfVl9PIiwiQ19UX0FfTyIsIkNfUl9WQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRUFMX08iLCJDX0NMX0VYUF9PIiwiQ19UX0VBTF9PIiwiQ19VUF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVVBfQV9PIiwiQ19DTF9BU19PIiwiQ19VX0VfTyIsIkNfT19WX08iLCJDX1JTX0VfTyIsIkNfVV9VQkxfTyIsIkVTUE9SVCIsIkNfTUVfRVhQX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9FWFBfTyIsIkNfQ0xfQkxfTyIsIkNfTUVfRUFQX08iLCJDX0NMX0NBTF9PIiwiQ19VX1ZfTyIsIkNfTUVfTUFfTyIsIkNfTUVfVkFMX08iLCJDX0NMX0RTX08iLCJDX05SX0VfTyIsIkNfVF9BUkxfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiI1NDY5NWYwMi0xZTlhLTQ5ODUtYWU0MS1lNjk0Y2UwYjZmODAiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJzdXBlciBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTQyNTQyMzIiLCJnaXZlbl9uYW1lIjoic3VwZXIgYWRtaW4iLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZmFtaWx5X25hbWUiOiIiLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYWRtaW5Ac2F1ZGllc3BvcnRzLnNhIiwiY2lkIjoiMV9TVENTX0NVU1QifQ.MF5N5Yf9HomXG9UtlekyZF2rTTW8zNWf8JVpGaSMqDB2_VUiRs_AyAcAqw6x48qiG9dRmbmb4N-KxUv5AjnTatZRlDuO3fDiM2hSCoMPSjdDladCuh8p2nC3f2M4mGSAZpY2gJV7Cdiqyu-432hg9z8ckoQ065Q_pkxcGw9pVppFG1-Jae5gZdYk7DaQWLESGGQj3JgoVGBNaxY4cLGADZ3xiYQr3i9fDFc9D6h-HtHGZI8qwlsbkGgVsNL3JnR8qm2oxlDgGjZ1-F7D5ZRlSxPEkkAWXVNMGRMi6iWCUH7SWThGW1-4H53U5S_RhjuYss4Dw1qKohd-tTHB5SyDrQ</value>
      <webElementGuid>a19c8304-4fe4-4074-a8fd-cd1205096d50</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>57a3ecf0-9f32-4faf-ab64-a0b676c3bbba</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>26a075bc-b9ec-4278-a5a9-9d70d450fb37</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>fe4edcdf-3eea-4d07-b491-03aab6d4ab66</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>bd8e2a5b-a19e-43e2-8be0-b96a03eaa1b7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/account/profiles/edit/4e6cdc1e-3bee-4946-98c4-14a99d3999bd</value>
      <webElementGuid>19d11a99-b893-45cb-b197-1264e7fc8802</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>e864f291-1631-4dd5-94ac-abf041076931</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>33e4877d-ea83-4dbe-9e25-8d18a6bf1522</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>8a44aff7-77eb-4d1a-8497-de89a5336b9b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</value>
      <webElementGuid>c2e55628-f22d-49be-910b-0aa53d9ea629</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;117&quot;, &quot;Not;A=Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;117&quot;</value>
      <webElementGuid>606b8e21-3159-43fd-bb69-b01efb94355e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>a4d8c251-4571-4ac9-b0f2-6caf8bc78cb6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>13e2278b-d367-413e-b99c-33819becdccb</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/uaa/profile/4e6cdc1e-3bee-4946-98c4-14a99d3999bd</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
