<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>DeleteContentCreator</name>
   <tag></tag>
   <elementGuidId>06a527c1-e4ab-4ad3-833e-02f4310fb900</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>82e001f2-020f-440d-bf9c-e7a4f93e76f2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>e4ba181b-ffc8-4da4-a70a-af336a01b699</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTg3NDI1NDQsImlhdCI6MTY5ODczODk0NCwiYXV0aF90aW1lIjoxNjk4NzM4OTQzLCJqdGkiOiIzYzIyYmIzNS04MDU2LTQ5ZDgtOWFmZS1iNDVkOWIxODcxMDciLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZWNhN2M4Zi0xYWFlLTRiZDAtOGFmYi00YmE0YmZhZGE3ZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjQ1ZmQyMDMwLTE3NGUtNDUzNS04ZDUxLWVmMmViMmQ3MGI4NiIsInNlc3Npb25fc3RhdGUiOiIzOTQxMmY5ZS1hOWRlLTQ0MDctOTRmMS0zN2M2NDIwMDQzMDIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX0NMX0VNWV9PIiwiQ19DTF9DQUxfTyIsIkNfVF9EU19PIiwib2ZmbGluZV9hY2Nlc3MiLCJDX0NMX01BX08iLCJDX0NMX0FTX08iLCJDX0NMX1ZNWV9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiMzk0MTJmOWUtYTlkZS00NDA3LTk0ZjEtMzdjNjQyMDA0MzAyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiQXV0b21hdGlvbiBDbHViIG93bmVyIGFjY291bnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTg4ODg4ODAwIiwiZ2l2ZW5fbmFtZSI6IkF1dG9tYXRpb24gQ2x1YiBvd25lciBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NsdWJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.eLAhfM1Yn_iznLKKfstJIYuM4iHGdYPqIhDg9xXmXaAh7F0nIJwScacMVde4eg8v_bccm0yQwsla1JOtb5Ejf6QKd4oSRwjEvq8swtP5uwP_y00O4D-DMKo7fearU3Ca6sqpRXbxW_ytTSxYZ-YCPyghJCXkDZyeqPAYw90Ou1TwINwRMQOew6gK0U6r6cNHx7QcGU5cRhzw1BcvDF-XnktUzFrvUeLClnXlpD8XmrefQlyvtOeBTGciZwkVzaOOPFI4kRDFGCsgiiC3OwJPOuZv6oRpZRHhZiGdh4W0yhFCykculTv1wLFGyaumYYltg6jtd8eD50wYZn1zuP-m6A</value>
      <webElementGuid>7b62f84e-625e-4f4e-b88d-fd052eadafcf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>d5fc74e9-1a63-4d14-ab50-84646cb362d6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>18691258-6982-4891-b2c9-1c46a0aeea97</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>968f4bfd-ce2f-460d-ad36-23db618f9f35</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/club/content-creators</value>
      <webElementGuid>829ba9fc-8a98-4af1-aa07-e1c2c984fdb7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>29980716-51a5-485a-abe5-735f06592fe0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>b78ce0ae-0424-4c2a-9c0c-ad9436cbb1c6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>1ec3b554-c759-40a2-bd8d-03ac288a8b8b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36</value>
      <webElementGuid>1781ae88-71c8-4673-8523-8b077fbb8d51</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;118&quot;, &quot;Google Chrome&quot;;v=&quot;118&quot;, &quot;Not=A?Brand&quot;;v=&quot;99&quot;</value>
      <webElementGuid>b4d8073e-28a0-43b0-98e9-141458e1f592</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>d9876580-d391-4d16-b83a-7d8a331498c4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>16db5c55-1886-4049-9a38-1e4ac5c376d5</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>DELETE</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/clubs/content-creator?email=Auto_content@mailinator.com&amp;invStatus=ACCEPTED</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
