<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get invitation list by status for content creator</name>
   <tag></tag>
   <elementGuidId>b2e3a4f1-1a46-45ac-9deb-e96c1d9baa7e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>cd3a11a8-da14-4e17-b238-dff7d6316593</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>753bf7d0-1794-4bd4-a1ea-65710c75f743</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTkxODI3MjEsImlhdCI6MTY5OTE3OTEyMSwiYXV0aF90aW1lIjoxNjk5MTc5MTIwLCJqdGkiOiJmMjNhNDg5Ni0wNTRmLTRlZGUtYTMxNS0zYWY4NTVhMzkwMmQiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI1ZjAwMjdjNC0zYzlkLTRmN2UtYTkzNS02YjI4YzA2NzVkZDciLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjVjNWMwNDJjLWI5NmItNDYzZS04MjNkLWM1M2JhNTY1NGVkMSIsInNlc3Npb25fc3RhdGUiOiJjYjZkZWNlNS0xNTFiLTQ5MmItOWI4OC00NDc0NTAzZDJlYWIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX1RfRFNfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19DTF9WTVlfTyIsIkNfTUVfRFNfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19NRV9WQUxfTyIsIkNfQ0xfRFNfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJjYjZkZWNlNS0xNTFiLTQ5MmItOWI4OC00NDc0NTAzZDJlYWIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJjb250ZW50IGNyZWF0b3IgYXV0byBhY2NvdW50IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiKzk2NjU2Nzg5NDMyMyIsImdpdmVuX25hbWUiOiJjb250ZW50IGNyZWF0b3IgYXV0byBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NvbnRlbnRfaW52aXRlQG1haWxpbmF0b3IuY29tIiwiY2lkIjoiMV9TVENTX0NVU1QifQ.nqvskDEpJhWPa9aENqkd-8GSqhTBvIR-9OusKjBtmPABxNbz4yPCYIb3iI2Bpq0NnOqJndibJ_sAT1Zowrf3Xl38wAegqL3TVMC94l9I7LdTFHZk_uO6yMv4L0h_Mak5Cc--683vjtMjanR4_GQbdhod6uJMXOSUw3Spn1wXOU37uEC9usCC9AjIHM-UYeYDhDLKnQHJISA40UxLjGgl2moQcGySSmxB6qPJVWw7mb94flwO0i8ZOnpRgRsozcI5VmkZJ8UdmgMB6bpCO1-UcjdJfmwRRGgpyLzsSDIF08yV62YNPPsV5d_DWpUNZJdwyHIynyB9_ISTk5nUYLFjLw</value>
      <webElementGuid>5ee09985-0297-46a2-81af-b832e85e392c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>ddaa9b1d-3ad7-45b6-8cc7-ec5b88666805</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>6a0071da-a890-4451-8441-bf2337c75dfb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/invitations/received/view/ad861745-d9e6-4257-a785-986b0b283695</value>
      <webElementGuid>c0280c97-b204-4012-9598-7cccc96b19f1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>46002828-1ea9-4414-837b-49c4a475f13a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>4f5cc7f4-e5bd-460a-913f-74c39d5d69ba</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>e093bab1-e25b-4a2c-92b2-77b821c99471</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36</value>
      <webElementGuid>481ade50-faef-4345-bf9f-10ed894bc355</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;118&quot;, &quot;Google Chrome&quot;;v=&quot;118&quot;, &quot;Not=A?Brand&quot;;v=&quot;99&quot;</value>
      <webElementGuid>cf307b55-2d17-4707-be80-5c81ad168da1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>770878c0-07ec-46eb-b333-4fd75297fe4a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>fc7f8bd8-a0c3-4c61-9513-1db0d2e0b19d</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/invitation?page=0&amp;size=10&amp;sort=creationDate,desc&amp;type=RECEIVED</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
