<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ApproveContractRequestByAdmin</name>
   <tag></tag>
   <elementGuidId>7e0455c5-652b-4b1e-823e-2fbd557b31bc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>19037ae0-7f09-4aef-afed-c85a77f7e3be</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>6533b1af-af71-48b2-93c1-52e240c7ac42</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDczOTg4NzIsImlhdCI6MTcwNzM5NTI3MiwiYXV0aF90aW1lIjoxNzA3Mzk0ODU5LCJqdGkiOiI1ZTY5OTJjOC04YWQwLTQ4OGYtOTZlYS01ZDM4YmIzZWM2NWQiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjlkMTQ0ODA5LWQ5ZDAtNGQxYy1iMzE5LWFkZDBmNzIyMDY4MSIsInNlc3Npb25fc3RhdGUiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX0VWX0xfTyIsIkNfVVBfRF9PIiwiQ19UQ19FX08iLCJDX1BBUl9DQU5fTyIsIkNfQ0xfRU1ZX08iLCJDX0NSUV9FX08iLCJDX1RfVl9PIiwiQ19QQVJfRV9MX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19QQVJfRV9PIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19FVlJfRV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX1RXX0VfTyIsIkNfTUVfVU5CX08iLCJDX01FX0RTX08iLCJDX1ZfQVNfTyIsImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfQUxfRVhQX08iLCJDX0NMX1ZfTyIsIkNfVF9BX08iLCJDX0VWX0VfTyIsIkNfUl9WQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRUFMX08iLCJDX0NMX0VYUF9PIiwiQ19UX0VBTF9PIiwiQ19VUF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVVBfQV9PIiwiQ19DTF9BU19PIiwiQ19VX0VfTyIsIkNfT19WX08iLCJDX1JTX0VfTyIsIkNfVV9VQkxfTyIsIkVTUE9SVCIsIkNfTUVfRVhQX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9SQ19PIiwiQ19QQVJfTF9PIiwiQ19UX0VYUF9PIiwiQ19QQVJfSVNVX08iLCJDX0NMX0JMX08iLCJDX01FX0VBUF9PIiwiQ19DTF9DQUxfTyIsIkNfTUVfVkVSX08iLCJDX1VfVl9PIiwiQ19NRV9NQV9PIiwiQ19BUkNfRV9PIiwiQ19NRV9WQUxfTyIsIkNfRVZfQ0FOX08iLCJDX0NMX0RTX08iLCJDX05SX0VfTyIsIkNfVF9BUkxfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJzdXBlciBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTQyNTQyMzIiLCJnaXZlbl9uYW1lIjoic3VwZXIgYWRtaW4iLCJsb2NhbGUiOiJlbiIsInJpZCI6ImN1c3RfZXNwb3J0cy5jb20iLCJmYW1pbHlfbmFtZSI6IiIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhZG1pbkBzYXVkaWVzcG9ydHMuc2EiLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.JIsKcP-hk4xHaLSAiPTiEAKSHM90GRuM_QrFdQBuzF7_dccDKcaH01YlULjlZG9VTwW_N4u2eFzpzoXMKICeKdylNR8mTHRm7bNDB_BcQxWS6xPSrC_jRpWblvnpYneOjhi9CZmuWBTKq3jmlpz9FRX8u0IXfZETLIJ_9ot1o2BLYyMjUdgQQRxbaTaouYhujxDqweMXELL8w_rOeDVTK5DcdnG3efmvgie_Oj-BJI1TZe6Vx5V9OTZOqwQhbHFk_pPbJerH3W5AN2M0fRmnKM9hFaomvUzO-IQfzsNGhHMxUCO93a6AapaoCI4h4Y5MmD5wx293btEAt6xEIYf88A</value>
      <webElementGuid>7d2cb23f-1618-44d7-af1b-ab4df53d6eed</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>2ceb7fd4-5937-40ee-afac-add977f77c8c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>bcccc9e2-7734-4a13-930a-78094a608674</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>2694080a-1bef-4318-adf6-bf909c37493f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>4d90e110-dd51-4e63-89ec-dbda79fa7c50</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/crm/requests/contract-details/c88e0846-1324-4521-ae87-ef32b3a3d3fb</value>
      <webElementGuid>0d2cb49e-3c4b-495e-9ecd-585353234009</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>becc6949-396b-4b9b-b185-e4e22a3acca6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>5548a2b3-ca7e-4d39-a2a6-2732298a97f5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>af979979-c765-4a00-830c-8c007cc8a835</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>d3c073e3-7091-437b-8789-fee2aaaccd2c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>c44372f7-1b34-4ee9-80be-4b276d5be107</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>3e8cc8f0-022f-45f2-846a-a29eb3f25029</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>de5bfdb7-be30-4e25-9674-89410d7e3bf1</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/member-contract/approve/c88e0846-1324-4521-ae87-ef32b3a3d3fb</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
