<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Approve  contract invitation</name>
   <tag></tag>
   <elementGuidId>c1d04164-fde8-4526-a242-e7061c006b3c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;1c1424a6-2f35-4f83-8ab4-a499a639a622&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8a7b941a-27ed-49a4-82e4-0fcad9409670</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9</value>
      <webElementGuid>b4eddf33-c785-4f60-a009-8fe30c52b06a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDcxNDYyNzAsImlhdCI6MTcwNzE0MjY3MCwiYXV0aF90aW1lIjoxNzA3MTQxNTM2LCJqdGkiOiI5MWE5YmJiMy00MWYzLTQ3MzgtYmQ0Ny1iZjYyZjg3ZjZhMzUiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzNjkzZjA3NC0xODZhLTQ3YjUtYjE5Yi1mN2EzYWEyZjE3NzMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6ImQ3ODU1YjQ4LTlkZWMtNGUyZC1iZjBhLTM4ZDdkMDczY2Y3MCIsInNlc3Npb25fc3RhdGUiOiJmYTQ5N2NlNy00NjNjLTQ4NzEtYmNiOC04NTBlOGU1ZDM1MmMiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRFNfTyIsIkNfVF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVF9NVEFfTyIsIkNfVF9BUl9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZmE0OTdjZTctNDYzYy00ODcxLWJjYjgtODUwZThlNWQzNTJjIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiYXV0b21hdGlvbiBwbGF5ZXIgYWNjb3VudCIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1Nzc3Nzc3MDAiLCJnaXZlbl9uYW1lIjoiYXV0b21hdGlvbiBwbGF5ZXIgYWNjb3VudCIsInJpZCI6ImN1c3RfZXNwb3J0cy5jb20iLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYXV0b19wbGF5ZXJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.wFQLOY1Sv6F1ZY6MlfX4N3r6v6ZsDoCPiUoDJNojopDb2wc97icy-VtyCF2vgAhNPUh3R4BspT4cl7hFnT6Lt2AVySfoOz-OEIf9srJVjnEBt8LBfDeubQGEigCzMWbXt7hPJJkNFmttA2EP_3SaX0HfRgChD3V_EKeWyyAAnNeTvlCnojQAFPtNOM-CKyk0l5aiRfRVYO1pgSA6yr3nUWytIRZto_ELa8199EGM23DkxQFQ8wK6X2h7xdjSbUvIrDv0sttBC4TAlW7zSydSgeSk0i8-WkqcI4-AAJHMbO4UtXU6OTa4AoWkuuzgxYe9a7ZTD0Pc-jW3UzqdRox-gQ</value>
      <webElementGuid>31db1d5f-4b98-45c0-8e0d-77cf13357090</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>1177bc72-f1da-4651-b426-fe6dadceeb10</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>text/plain</value>
      <webElementGuid>58598d59-e796-43e2-aa63-211844220bcc</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>358072e6-cd25-4fd3-9e5c-5049e5851148</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>77267397-4c3f-415c-af11-6cbb4b0edda7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/invitations/received/view/1c1424a6-2f35-4f83-8ab4-a499a639a622?contractSystemId=d09687f8-5301-406b-800a-7c1172673e62</value>
      <webElementGuid>ab92352e-85fc-4344-b4ab-3bfcdbd25ad8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>92c70a35-dda3-45aa-8c2d-c8e448fabc23</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>0f2a64c5-b8d7-4fd2-9219-260122a0d2dc</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>056919f5-0608-42c0-8f56-20efbe5cb4df</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>f67e27f8-8974-44c7-84a5-2c0ccf453897</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>1cf17873-a17e-48f0-9898-cadb3b322261</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>a97752a6-7cf8-4182-89fb-218a02cd28d9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>a58f6aaa-30d6-4cfb-9429-d5dda5dacb60</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/invitation/approve/contract/1c1424a6-2f35-4f83-8ab4-a499a639a622</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
