<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Get invitationId for specific contract</name>
   <tag></tag>
   <elementGuidId>b43f7d0f-c63d-4879-8368-2f42df16f2f2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>31d4b47c-91d5-401e-a081-083e96f866e3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>acccc30f-6d14-4795-81bb-a2fd33639d41</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDcxNDUxOTgsImlhdCI6MTcwNzE0MTU5OCwiYXV0aF90aW1lIjoxNzA3MTQxMzk2LCJqdGkiOiI1YzI2ZDJhZC0wNDE0LTQ2MzItYWRjNC1mZGU1YzJhZDI1N2MiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZWNhN2M4Zi0xYWFlLTRiZDAtOGFmYi00YmE0YmZhZGE3ZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjljNTUxOTdiLTNmNWEtNGMyYS05MTY3LThmZWFmZmUxMjc3YSIsInNlc3Npb25fc3RhdGUiOiJlYmMzZTBmOS05NDIxLTRiMzctYjVlNS01YzhlNWQ4MjgzMmMiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX0NMX0VNWV9PIiwiQ19DTF9DQUxfTyIsIkNfVF9EU19PIiwib2ZmbGluZV9hY2Nlc3MiLCJDX0NMX01BX08iLCJDX0NMX0FTX08iLCJDX0NMX1ZNWV9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWJjM2UwZjktOTQyMS00YjM3LWI1ZTUtNWM4ZTVkODI4MzJjIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiQXV0b21hdGlvbiBDbHViIG93bmVyIGFjY291bnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTg4ODg4ODAwIiwiZ2l2ZW5fbmFtZSI6IkF1dG9tYXRpb24gQ2x1YiBvd25lciBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NsdWJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.Snc-ByFD_AELrYukzhpVIGYhgAEJGmc47sjbVdiZ7_R4r4eVODtCcamCyeTe-hvV2ahBAYBtv_MwYMThYn9TCDosMWb7_DjvZmTOD2hOUU6DcqF-DVtAI7we6I7BhhwaUIMZKhvSZ1d2YVCnQ9K4rvYGanBKjRgrjLZjVOxqQhE3-DXoROe-3rM9BKYXmidT58WFOg_YFe3YyhPMOFH82OO3BCBmtOXgEpSZPFiXCt9Ln1b0dn42gTfbNv0lxpdJ03wLg8MrdL1qP4P3RWDrxhTf0YWnBAFOjZ006LJT2gHw3yeUh43WmvjjN6T__JfuSmiunHDNg1HbYSCi6IJW-g</value>
      <webElementGuid>f4338c6b-c465-4a92-9bbd-6cb4c207909b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>4fcf6527-8f6a-49de-ac16-0d5b7d22321b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>f61405d9-d654-44a6-a87f-8a49faca2bda</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/teams/88df92d7-628e-42fe-b53f-edb54e70225f/contracts</value>
      <webElementGuid>5e884a05-eae6-477b-a3c7-ca4f8b270604</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>b3e9f930-013c-4bab-a2ab-7f88e818b3de</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>2574434b-66dc-4691-883d-39e26ef205e9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>b4fc70cd-1fc9-469e-b52a-a6439b62d860</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>df897a3f-4ceb-47e2-b282-11e1b99d9c1e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>2bc8c505-8873-426b-9490-33ba3b11d4b3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>03593cf5-c249-4865-a384-e7b7a9434fd5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>23696951-251b-468c-990e-4469e6270249</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/member-contract/contracts/88df92d7-628e-42fe-b53f-edb54e70225f</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
