<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>getAllContractRequestsForSpecificteam</name>
   <tag></tag>
   <elementGuidId>b89e8c34-0f7d-448b-83cb-d9e480e8338a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>cf9347c8-f9be-4f6b-ac53-56377f100511</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>7e22b4b2-5644-4955-b0f1-277c6bcd0c8e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDczOTk2NzAsImlhdCI6MTcwNzM5NjA3MCwiYXV0aF90aW1lIjoxNzA3Mzk0ODU5LCJqdGkiOiI1N2Q3M2U2ZS1kN2FkLTQxM2UtYmQ3Ni03NjY3ZWY0M2Q2NGEiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6ImJiODE2ZTYyLTk5ZGEtNDc1NC1iM2MyLTQ1NzM0NDUzOTY1NyIsInNlc3Npb25fc3RhdGUiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX0VWX0xfTyIsIkNfVVBfRF9PIiwiQ19UQ19FX08iLCJDX1BBUl9DQU5fTyIsIkNfQ0xfRU1ZX08iLCJDX0NSUV9FX08iLCJDX1RfVl9PIiwiQ19QQVJfRV9MX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19QQVJfRV9PIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19FVlJfRV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX1RXX0VfTyIsIkNfTUVfVU5CX08iLCJDX01FX0RTX08iLCJDX1ZfQVNfTyIsImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfQUxfRVhQX08iLCJDX0NMX1ZfTyIsIkNfVF9BX08iLCJDX0VWX0VfTyIsIkNfUl9WQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRUFMX08iLCJDX0NMX0VYUF9PIiwiQ19UX0VBTF9PIiwiQ19VUF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVVBfQV9PIiwiQ19DTF9BU19PIiwiQ19VX0VfTyIsIkNfT19WX08iLCJDX1JTX0VfTyIsIkNfVV9VQkxfTyIsIkVTUE9SVCIsIkNfTUVfRVhQX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9SQ19PIiwiQ19QQVJfTF9PIiwiQ19UX0VYUF9PIiwiQ19QQVJfSVNVX08iLCJDX0NMX0JMX08iLCJDX01FX0VBUF9PIiwiQ19DTF9DQUxfTyIsIkNfTUVfVkVSX08iLCJDX1VfVl9PIiwiQ19NRV9NQV9PIiwiQ19BUkNfRV9PIiwiQ19NRV9WQUxfTyIsIkNfRVZfQ0FOX08iLCJDX0NMX0RTX08iLCJDX05SX0VfTyIsIkNfVF9BUkxfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJzdXBlciBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTQyNTQyMzIiLCJnaXZlbl9uYW1lIjoic3VwZXIgYWRtaW4iLCJsb2NhbGUiOiJlbiIsInJpZCI6ImN1c3RfZXNwb3J0cy5jb20iLCJmYW1pbHlfbmFtZSI6IiIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhZG1pbkBzYXVkaWVzcG9ydHMuc2EiLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.ASr_Duztuy6mkciZhbmGV8HDjItA4dY7qnYoypbmBaF69eDx_3WUMCCmTqSrWAqVnjiCyiYmBwb5nvUwht4GKeIMuk9drl4EiE5fc1iSlPdVO11kKywAZznihszYfUXBrp7bDkDOXWZJkMMkCkgDQHMym87W2Wc8HSUCm2T6WN6uJ-LZiho6VfQZuAgxP4HBKpmh2WnC5O3GmMCxmE_UmjEWYi-rz8QXk0SH9NCN2CNjtsu-usz_-GWdR-ufS8OTNJnfJ_wxsXM23_lioD2L0XGlLBv9BvUxVYlG86SWci13E6nor-QsufWlScqX8_53pRzGt0gNua7NofE31lyt3A</value>
      <webElementGuid>fc5344ee-f696-49a4-be5b-10ac403965ef</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>740347d9-ff5b-428d-a816-6f99686d1c06</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>dbc226fb-f225-44bf-8459-40c04224071b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/crm/requests/view-contract-requests/918720f7-ea5f-4f38-a5fc-3183158148f9</value>
      <webElementGuid>68cb6d06-5ae9-4c17-81e7-e6d95db76e58</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>232fcb9c-6d92-4312-8369-e901a05f24a8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>a8266fd6-180c-4cc6-9f13-c6d7ebbb6ec9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>31a7841a-d6b3-497b-9d47-cebf115c044f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>6fc8ad34-a366-45b7-a7ca-a0bcb86e9215</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>2abdca6e-9ed6-4e2e-969d-723fdcb0317f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>47850b0d-5ca2-4d6d-a050-232086bf6d88</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>f8eb0320-2e7b-4e7f-bbf7-3eac35a8cddc</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/member-contract/team-requests/6dd634d4-9f02-4484-a361-2f57d635667f</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
