<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(5)</name>
   <tag></tag>
   <elementGuidId>b10c216d-ae10-4fbb-948a-c7fbf84a7f4e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;id\&quot;: 8,\r\n    \&quot;name\&quot;: \&quot;Test customer\&quot;,\r\n    \&quot;nameAr\&quot;: \&quot;اختبار العميل\&quot;,\r\n    \&quot;primaryContactName\&quot;: \&quot;testcustomer\&quot;,\r\n    \&quot;primaryContactPhone\&quot;: \&quot;00966222222222\&quot;,\r\n    \&quot;primaryContactEmail\&quot;: \&quot;testcustomer@cuvox.de\&quot;,\r\n    \&quot;notes\&quot;: \&quot;ggg\&quot;,\r\n    \&quot;pkg\&quot;: {\r\n        \&quot;id\&quot;: 3,\r\n        \&quot;nameEn\&quot;: \&quot;BG\&quot;,\r\n        \&quot;note\&quot;: \&quot;\&quot;,\r\n        \&quot;systemId\&quot;: \&quot;65af27bf-2b60-4790-81ce-d5d691b292e7\&quot;,\r\n        \&quot;reserved\&quot;: false,\r\n        \&quot;outdated\&quot;: false\r\n    },\r\n    \&quot;country\&quot;: {\r\n        \&quot;id\&quot;: 1,\r\n        \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n        \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n    },\r\n    \&quot;region\&quot;: {\r\n        \&quot;regionCode\&quot;: \&quot;PRV1\&quot;,\r\n        \&quot;regionName\&quot;: \&quot;Riyadh\&quot;,\r\n        \&quot;regionName_ar\&quot;: \&quot;الرياض\&quot;,\r\n        \&quot;country\&quot;: {\r\n            \&quot;id\&quot;: 1,\r\n            \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n            \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n        }\r\n    },\r\n    \&quot;city\&quot;: {\r\n        \&quot;cityCode\&quot;: \&quot;RIY036\&quot;,\r\n        \&quot;cityName\&quot;: \&quot;Riyadh\&quot;,\r\n        \&quot;cityName_ar\&quot;: \&quot;الرياض\&quot;,\r\n        \&quot;region\&quot;: {\r\n            \&quot;regionCode\&quot;: \&quot;PRV1\&quot;,\r\n            \&quot;regionName\&quot;: \&quot;Riyadh\&quot;,\r\n            \&quot;regionName_ar\&quot;: \&quot;الرياض\&quot;,\r\n            \&quot;country\&quot;: {\r\n                \&quot;id\&quot;: 1,\r\n                \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n                \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n            }\r\n        }\r\n    },\r\n    \&quot;sector\&quot;: {\r\n        \&quot;id\&quot;: 2,\r\n        \&quot;sectorName\&quot;: \&quot;Business\&quot;,\r\n        \&quot;sectorName_ar\&quot;: \&quot;تجاري\&quot;\r\n    },\r\n    \&quot;createdAt\&quot;: \&quot;2024-02-01T13:48:27.602Z\&quot;,\r\n    \&quot;crNumber\&quot;: \&quot;12331\&quot;,\r\n    \&quot;industry\&quot;: {\r\n        \&quot;id\&quot;: 2,\r\n        \&quot;industryName\&quot;: \&quot;Banking \u0026 Finance\&quot;,\r\n        \&quot;industryName_ar\&quot;: \&quot;الخدمات المصرفية والمالية\&quot;\r\n    },\r\n    \&quot;type\&quot;: {\r\n        \&quot;id\&quot;: 3,\r\n        \&quot;custTypeName\&quot;: \&quot;Government\&quot;,\r\n        \&quot;custTypeName_ar\&quot;: \&quot;حكومة\&quot;\r\n    },\r\n    \&quot;managed\&quot;: true,\r\n    \&quot;accountManager\&quot;: \&quot;accountmanager\&quot;,\r\n    \&quot;accountManagerContact\&quot;: \&quot;00966222121222\&quot;,\r\n    \&quot;accountManagerEmail\&quot;: \&quot;accountmanager@cuvox.de\&quot;,\r\n    \&quot;systemId\&quot;: \&quot;6000_ent\&quot;,\r\n    \&quot;userName\&quot;: \&quot;testcustomer\&quot;,\r\n    \&quot;active\&quot;: true,\r\n    \&quot;deleted\&quot;: false,\r\n    \&quot;createdBySystemId\&quot;: \&quot;72353fe1-b6f4-4696-a9b0-beb17e9f5b4b\&quot;,\r\n    \&quot;createdByName\&quot;: \&quot;stcsadmin\&quot;,\r\n    \&quot;updatedAt\&quot;: \&quot;2024-02-01T14:28:19.960Z\&quot;,\r\n    \&quot;updatedBySystemId\&quot;: \&quot;72353fe1-b6f4-4696-a9b0-beb17e9f5b4b\&quot;,\r\n    \&quot;updatedByName\&quot;: \&quot;stcsadmin\&quot;,\r\n    \&quot;root\&quot;: false,\r\n    \&quot;reserved\&quot;: false,\r\n    \&quot;waslActivity\&quot;: \&quot;\&quot;,\r\n    \&quot;migrated\&quot;: false,\r\n    \&quot;crDateType\&quot;: null,\r\n    \&quot;packageValidations\&quot;: {\r\n        \&quot;hasSfdaFeature\&quot;: false,\r\n        \&quot;hasTammFeature\&quot;: false,\r\n        \&quot;hasWaslFeature\&quot;: false\r\n    },\r\n    \&quot;crDtHijri\&quot;: null,\r\n    \&quot;tfastatus\&quot;: \&quot;1\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json, text/plain, */*</value>
      <webElementGuid>e56e1e41-540d-42df-9efc-00f658e400b6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>78039d01-20fa-4313-93b0-8566527f9d8f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer 9a94aafe-2849-45a1-ba3a-2a15b868f229</value>
      <webElementGuid>5a5c25fb-d702-4c87-9ebc-b3b42bb29b1f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>75c98323-220a-4e3d-8955-90b7c44c0c46</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0d829e7b-4f5f-48f0-be00-7e2547cfebfb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>6f6283ec-d180-427d-a469-bf443e4df82d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>FMSAccessGroups</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a2a7f70a-d969-42a8-a51d-4dd30cd39e2c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa</value>
      <webElementGuid>b7172d1a-2213-4c3d-8fe8-633b8e0051fb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa/apps/admin/customers/edit/6000_ent</value>
      <webElementGuid>5ebf9bc0-f97f-4dc4-8099-afa2be9a9c7f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>8b81b228-d9e0-451f-b02b-3f8ed1fa4af7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>30ddda31-ba6b-4825-a26f-5e41e7545831</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>1464dcef-200a-4543-956f-50fe64757796</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</value>
      <webElementGuid>3c4516e1-4e30-444a-918e-728f74c6822c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not_A Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;120&quot;, &quot;Google Chrome&quot;;v=&quot;120&quot;</value>
      <webElementGuid>ab565981-03af-41ce-bcd2-78dd6f5884f9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>a867933e-550c-4468-a4d3-958944db978c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>1895ab67-7abc-413d-b97c-371c328b15af</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://migration-myfleet.stcs.com.sa/api/gw/v1/customer/</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
