<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(7)</name>
   <tag></tag>
   <elementGuidId>ba74dc78-07df-41dc-8acf-fda5ac534cc0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;id\&quot;: 8,\r\n    \&quot;name\&quot;: \&quot;Test customer\&quot;,\r\n    \&quot;nameAr\&quot;: \&quot;اختبار العميل\&quot;,\r\n    \&quot;primaryContactName\&quot;: \&quot;testcustomer\&quot;,\r\n    \&quot;primaryContactPhone\&quot;: \&quot;00966222222222\&quot;,\r\n    \&quot;primaryContactEmail\&quot;: \&quot;testcustomer@cuvox.de\&quot;,\r\n    \&quot;pkg\&quot;: {\r\n        \&quot;id\&quot;: 3,\r\n        \&quot;nameEn\&quot;: \&quot;BG\&quot;,\r\n        \&quot;note\&quot;: \&quot;\&quot;,\r\n        \&quot;systemId\&quot;: \&quot;65af27bf-2b60-4790-81ce-d5d691b292e7\&quot;,\r\n        \&quot;reserved\&quot;: false,\r\n        \&quot;outdated\&quot;: false\r\n    },\r\n    \&quot;country\&quot;: {\r\n        \&quot;id\&quot;: 1,\r\n        \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n        \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n    },\r\n    \&quot;region\&quot;: {\r\n        \&quot;regionCode\&quot;: \&quot;PRV1\&quot;,\r\n        \&quot;regionName\&quot;: \&quot;Riyadh\&quot;,\r\n        \&quot;regionName_ar\&quot;: \&quot;الرياض\&quot;,\r\n        \&quot;country\&quot;: {\r\n            \&quot;id\&quot;: 1,\r\n            \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n            \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n        }\r\n    },\r\n    \&quot;city\&quot;: {\r\n        \&quot;cityCode\&quot;: \&quot;RIY036\&quot;,\r\n        \&quot;cityName\&quot;: \&quot;Riyadh\&quot;,\r\n        \&quot;cityName_ar\&quot;: \&quot;الرياض\&quot;,\r\n        \&quot;region\&quot;: {\r\n            \&quot;regionCode\&quot;: \&quot;PRV1\&quot;,\r\n            \&quot;regionName\&quot;: \&quot;Riyadh\&quot;,\r\n            \&quot;regionName_ar\&quot;: \&quot;الرياض\&quot;,\r\n            \&quot;country\&quot;: {\r\n                \&quot;id\&quot;: 1,\r\n                \&quot;countryName\&quot;: \&quot;KSA\&quot;,\r\n                \&quot;countryName_ar\&quot;: \&quot;المملكة العربية السعودية\&quot;\r\n            }\r\n        }\r\n    },\r\n    \&quot;sector\&quot;: {\r\n        \&quot;id\&quot;: 2,\r\n        \&quot;sectorName\&quot;: \&quot;Business\&quot;,\r\n        \&quot;sectorName_ar\&quot;: \&quot;تجاري\&quot;\r\n    },\r\n    \&quot;createdAt\&quot;: \&quot;2024-02-01T13:48:27.602Z\&quot;,\r\n    \&quot;crNumber\&quot;: \&quot;12331\&quot;,\r\n    \&quot;industry\&quot;: {\r\n        \&quot;id\&quot;: 2,\r\n        \&quot;industryName\&quot;: \&quot;Banking \u0026 Finance\&quot;,\r\n        \&quot;industryName_ar\&quot;: \&quot;الخدمات المصرفية والمالية\&quot;\r\n    },\r\n    \&quot;type\&quot;: {\r\n        \&quot;id\&quot;: 3,\r\n        \&quot;custTypeName\&quot;: \&quot;Government\&quot;,\r\n        \&quot;custTypeName_ar\&quot;: \&quot;حكومة\&quot;\r\n    },\r\n    \&quot;managed\&quot;: true,\r\n    \&quot;accountManager\&quot;: \&quot;accountmanager\&quot;,\r\n    \&quot;accountManagerContact\&quot;: \&quot;00966222121222\&quot;,\r\n    \&quot;accountManagerEmail\&quot;: \&quot;accountmanager@cuvox.de\&quot;,\r\n    \&quot;systemId\&quot;: \&quot;6000_ent\&quot;,\r\n    \&quot;userName\&quot;: \&quot;testcustomer\&quot;,\r\n    \&quot;active\&quot;: true,\r\n    \&quot;deleted\&quot;: false,\r\n    \&quot;createdBySystemId\&quot;: \&quot;72353fe1-b6f4-4696-a9b0-beb17e9f5b4b\&quot;,\r\n    \&quot;createdByName\&quot;: \&quot;stcsadmin\&quot;,\r\n    \&quot;updatedAt\&quot;: \&quot;2024-02-01T13:54:36.260Z\&quot;,\r\n    \&quot;updatedBySystemId\&quot;: \&quot;72353fe1-b6f4-4696-a9b0-beb17e9f5b4b\&quot;,\r\n    \&quot;updatedByName\&quot;: \&quot;testuser\&quot;,\r\n    \&quot;root\&quot;: false,\r\n    \&quot;reserved\&quot;: false,\r\n    \&quot;waslActivity\&quot;: \&quot;\&quot;,\r\n    \&quot;migrated\&quot;: false,\r\n    \&quot;crDateType\&quot;: null,\r\n    \&quot;packageValidations\&quot;: {\r\n        \&quot;hasSfdaFeature\&quot;: false,\r\n        \&quot;hasTammFeature\&quot;: false,\r\n        \&quot;hasWaslFeature\&quot;: false\r\n    },\r\n    \&quot;notes\&quot;: \&quot;bbbb\&quot;,\r\n    \&quot;crDtHijri\&quot;: null,\r\n    \&quot;tfastatus\&quot;: 1\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json, text/plain, */*</value>
      <webElementGuid>28c253a8-c69a-4c22-b581-730ccad962ed</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>039352f2-0686-41c1-8bfa-430838966fae</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer 1ae462c5-5b26-4295-9058-64302a90699d</value>
      <webElementGuid>240ff3d1-9b46-4f7d-9589-d02d1542b7e6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>3c614612-ad2e-4d1b-8f58-d0a97d0eecb0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8c48d3f8-7d66-44ac-85f0-ce1c955ce4aa</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>0bd826f2-026b-44c3-99c7-2d3bb564a190</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>FMSAccessGroups</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>12a37379-112b-41dc-ad66-8bf6cb3f03a3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa</value>
      <webElementGuid>aa5b8db4-4627-44ca-b890-a5c8fb361820</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa/apps/admin/customers/edit/6000_ent</value>
      <webElementGuid>a6f598d6-2ad4-43fa-8e54-bdca4ad96195</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>fa21f848-02be-40c7-83f0-93054e00ffde</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>2f2c01df-3199-4270-9b61-9826f46a6cd4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>1893abd9-7911-44ef-9304-5a2182dcfa0c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</value>
      <webElementGuid>766d10b6-cad2-41f8-b9e2-10e4c1b0a185</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not_A Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;120&quot;, &quot;Google Chrome&quot;;v=&quot;120&quot;</value>
      <webElementGuid>60dc26a8-d840-422a-a557-9d0724a027b4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>fdea9ae1-b1e5-4387-9a32-5b7de481f032</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>018cbcdf-c670-4ded-83e2-b615b9fa0240</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://migration-myfleet.stcs.com.sa/api/gw/v1/customer/</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
