<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request(4)</name>
   <tag></tag>
   <elementGuidId>adfa0b07-7d21-4869-96fd-59566ee73eb3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;id\&quot;: 10,\r\n    \&quot;createdBy\&quot;: \&quot;stcsadmin\&quot;,\r\n    \&quot;createdDate\&quot;: 1706798521267,\r\n    \&quot;email\&quot;: \&quot;testcustomer@mailinator.com\&quot;,\r\n    \&quot;login\&quot;: \&quot;testcustomer\&quot;,\r\n    \&quot;mobileNumber\&quot;: \&quot;00966222222222\&quot;,\r\n    \&quot;name\&quot;: \&quot;Test customer\&quot;,\r\n    \&quot;organizationId\&quot;: \&quot;6000_ent\&quot;,\r\n    \&quot;organizationName\&quot;: \&quot;Test customer\&quot;,\r\n    \&quot;organizationNameAr\&quot;: \&quot;اختبار العميل\&quot;,\r\n    \&quot;phoneNumber\&quot;: \&quot;00966222222222\&quot;,\r\n    \&quot;prefferedLanguage\&quot;: \&quot;English\&quot;,\r\n    \&quot;profileId\&quot;: 8,\r\n    \&quot;profileType\&quot;: \&quot;Admin Profile\&quot;,\r\n    \&quot;levelId\&quot;: \&quot;f931b15e-b024-4d3d-bd7b-f09f71b98379\&quot;,\r\n    \&quot;levelName\&quot;: \&quot;General Region\&quot;,\r\n    \&quot;levelNameAr\&quot;: \&quot;منطقة عامة\&quot;,\r\n    \&quot;systemId\&quot;: \&quot;a1bbb0ff-f4dc-4a12-975c-ab3cb99cdc9f\&quot;,\r\n    \&quot;resetKey\&quot;: \&quot;83971266602852344975\&quot;,\r\n    \&quot;resetDate\&quot;: 1706796671172,\r\n    \&quot;disableCluster\&quot;: false,\r\n    \&quot;sauthorities\&quot;: [],\r\n    \&quot;organizationLevelData\&quot;: {\r\n        \&quot;id\&quot;: 15,\r\n        \&quot;name\&quot;: \&quot;General Region\&quot;,\r\n        \&quot;nameAr\&quot;: \&quot;منطقة عامة\&quot;,\r\n        \&quot;dataOrganizationLevelSystemId\&quot;: \&quot;f931b15e-b024-4d3d-bd7b-f09f71b98379\&quot;\r\n    },\r\n    \&quot;organizationLevel\&quot;: {\r\n        \&quot;id\&quot;: 7,\r\n        \&quot;name\&quot;: \&quot;Region\&quot;,\r\n        \&quot;nameAr\&quot;: \&quot;منطقة\&quot;,\r\n        \&quot;organizationLevelSystemId\&quot;: \&quot;55ae7c26-4022-4515-a645-464ecef688f1\&quot;\r\n    },\r\n    \&quot;roleId\&quot;: \&quot;ROLE_SUPER_ADMIN\&quot;,\r\n    \&quot;reserved\&quot;: true,\r\n    \&quot;stationUser\&quot;: false,\r\n    \&quot;campusSystemId\&quot;: \&quot;\&quot;,\r\n    \&quot;stationId\&quot;: \&quot;\&quot;,\r\n    \&quot;migratedUser\&quot;: false,\r\n    \&quot;forceChangePassword\&quot;: false,\r\n    \&quot;allowOldTheme\&quot;: false,\r\n    \&quot;forceHelp\&quot;: false,\r\n    \&quot;userType\&quot;: \&quot;FLEET_USER\&quot;,\r\n    \&quot;lastPasswordChange\&quot;: \&quot;2024-02-01T14:17:55.569+00:00\&quot;,\r\n    \&quot;idleSession\&quot;: false,\r\n    \&quot;active\&quot;: true,\r\n    \&quot;assignedToActivetrip\&quot;: false,\r\n    \&quot;loggedinuser\&quot;: \&quot;stcsadmin\&quot;,\r\n    \&quot;notes\&quot;: \&quot;vvv\&quot;,\r\n    \&quot;profileSystemId\&quot;: \&quot;62233ca7-bd19-4fe6-aae4-bb09e7ddedcc\&quot;,\r\n     \&quot;tfastatus\&quot;: \&quot;1\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json, text/plain, */*</value>
      <webElementGuid>43b087b1-a0b0-4ead-9b37-9545d04006f2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>80cee0e4-85c6-426c-90c9-34078286eb51</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer 47fba79b-d780-4660-a575-fd76cbdf89aa</value>
      <webElementGuid>668f6aae-a5bb-49de-aa07-daa7f91c6dfa</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>c1fe2de0-1c67-48cb-8827-f205567761d5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0df13bb7-ec82-44cb-af4a-7731608cdf4a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>d717b423-289f-43f7-9076-57262d3c3520</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>FMSAccessGroups</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c7ae5475-1f71-4cbc-ab4a-b563d9ccb3a9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa</value>
      <webElementGuid>07e79c73-1d0f-4323-b5df-c9fe21d84478</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://migration-myfleet.stcs.com.sa/manage/users/edit/a1bbb0ff-f4dc-4a12-975c-ab3cb99cdc9f</value>
      <webElementGuid>5d29fe6e-b6c9-42b1-97ea-21a9f7f0b989</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>5f674f9f-4eb8-4842-8d2d-da1609aa3433</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>6b1f2815-40b0-405f-bf27-137dddbc04c4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>88575190-18e8-40d3-8ebb-751b2d63e579</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</value>
      <webElementGuid>00a2caae-5d20-413f-8ef1-2a5f609fd0cf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not_A Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;120&quot;, &quot;Google Chrome&quot;;v=&quot;120&quot;</value>
      <webElementGuid>9c913836-3ef3-404a-b517-9d5740a824c1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>a7e875b0-60dd-4875-8d52-f8c4d4756a93</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>d533c35b-ab51-407d-b717-470f470dc26d</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://migration-myfleet.stcs.com.sa/api/gw/admin/user/</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
