<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>uploadContract</name>
   <tag></tag>
   <elementGuidId>2751d129-2db1-4741-9e15-a9b17635736e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;teamSystemId\&quot;: \&quot;eb266b6c-0dc1-4e94-8954-cd4d417746e6\&quot;,\r\n    \&quot;memberSystemId\&quot;: \&quot;3693f074-186a-47b5-b19b-f7a3aa2f1773\&quot;,\r\n    \&quot;name\&quot;: \&quot;GjbbMtLWZI\&quot;,\r\n    \&quot;nameAr\&quot;: \&quot;عقد سإشؤةاظ\&quot;,\r\n    \&quot;gender\&quot;: \&quot;MALE\&quot;,\r\n    \&quot;memberStatusCode\&quot;: \&quot;EMPLOYEE\&quot;,\r\n    \&quot;countryId\&quot;: 6,\r\n    \&quot;birthDate\&quot;: \&quot;1995-09-24\&quot;,\r\n    \&quot;idTypeCode\&quot;: \&quot;NATIONAL_ID\&quot;,\r\n    \&quot;nationalId\&quot;: \&quot;406802871\&quot;,\r\n    \&quot;memberContractIdFile\&quot;: \&quot;esports/f1891a91-70be-4edc-a3ed-9faa7be3bdcf__pdfFile.pdf\&quot;,\r\n    \&quot;isSaudiEleague\&quot;: false,\r\n    \&quot;fromDate\&quot;: \&quot;2024-02-07\&quot;,\r\n    \&quot;toDate\&quot;: \&quot;2024-12-30\&quot;,\r\n    \&quot;salary\&quot;: \&quot;1234\&quot;,\r\n    \&quot;memberContractFile\&quot;: \&quot;esports/cafea70a-5bf0-46b7-aa77-34d48432e847__pdfFile.pdf\&quot;,\r\n    \&quot;termsAccepted\&quot;: true\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>b207a2b7-1dc4-4541-8b6a-5b83bc595979</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>ae7a3231-c566-4764-945e-28f157ebc281</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDcxNDUxOTgsImlhdCI6MTcwNzE0MTU5OCwiYXV0aF90aW1lIjoxNzA3MTQxMzk2LCJqdGkiOiI1YzI2ZDJhZC0wNDE0LTQ2MzItYWRjNC1mZGU1YzJhZDI1N2MiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZWNhN2M4Zi0xYWFlLTRiZDAtOGFmYi00YmE0YmZhZGE3ZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjljNTUxOTdiLTNmNWEtNGMyYS05MTY3LThmZWFmZmUxMjc3YSIsInNlc3Npb25fc3RhdGUiOiJlYmMzZTBmOS05NDIxLTRiMzctYjVlNS01YzhlNWQ4MjgzMmMiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX0NMX0VNWV9PIiwiQ19DTF9DQUxfTyIsIkNfVF9EU19PIiwib2ZmbGluZV9hY2Nlc3MiLCJDX0NMX01BX08iLCJDX0NMX0FTX08iLCJDX0NMX1ZNWV9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiZWJjM2UwZjktOTQyMS00YjM3LWI1ZTUtNWM4ZTVkODI4MzJjIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiQXV0b21hdGlvbiBDbHViIG93bmVyIGFjY291bnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTg4ODg4ODAwIiwiZ2l2ZW5fbmFtZSI6IkF1dG9tYXRpb24gQ2x1YiBvd25lciBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NsdWJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.Snc-ByFD_AELrYukzhpVIGYhgAEJGmc47sjbVdiZ7_R4r4eVODtCcamCyeTe-hvV2ahBAYBtv_MwYMThYn9TCDosMWb7_DjvZmTOD2hOUU6DcqF-DVtAI7we6I7BhhwaUIMZKhvSZ1d2YVCnQ9K4rvYGanBKjRgrjLZjVOxqQhE3-DXoROe-3rM9BKYXmidT58WFOg_YFe3YyhPMOFH82OO3BCBmtOXgEpSZPFiXCt9Ln1b0dn42gTfbNv0lxpdJ03wLg8MrdL1qP4P3RWDrxhTf0YWnBAFOjZ006LJT2gHw3yeUh43WmvjjN6T__JfuSmiunHDNg1HbYSCi6IJW-g</value>
      <webElementGuid>8e18cf39-508c-464c-978f-f7a0acfb514d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>0b431cca-225a-4463-a10b-d9810511a576</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>c5445c9f-2014-4c8e-8f91-c8d5a81c699d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>afa421f4-b881-4970-8fa2-0da0d3605ce8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>af70b960-36f8-4b58-a404-45b82cfc64de</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/teams/88df92d7-628e-42fe-b53f-edb54e70225f/contracts/3693f074-186a-47b5-b19b-f7a3aa2f1773/upload</value>
      <webElementGuid>3ee6e91c-74f1-45fd-a2f9-1c48b202286c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>ee4ae6ea-0175-4099-a421-0d901739b3b0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>4974a383-9981-4e04-b573-c8d5bd7b989a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>fbfd8ff1-f6ad-4160-88de-f871b89cb7b2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>a80ddd60-8782-46bf-b4de-3ec44b2521a1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>22631701-2e4a-4fdc-9e4e-09714b526843</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>e2606787-9b41-4241-9253-2cf8ee13bb82</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>487c4495-2692-455d-b09a-da478cd67c79</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/member-contract</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
