<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_-- HTML EMAIL BODY --</name>
   <tag></tag>
   <elementGuidId>b2771757-3657-4550-8b35-73ec655e2a4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='html_msg_body']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#html_msg_body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;html_msg_body&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e5f7e15c-78f7-4f85-a966-ae57b2d3c34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>f826f2b1-e404-4682-9a80-2a334921ecbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML Email Message Body</value>
      <webElementGuid>a5819fef-b5cc-4c79-a0d4-c1b988e6bff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>85771b20-f56e-474d-84dc-50fbaf6c4c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3b5f8397-fe29-4588-8e5d-92f6f49d9dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>60b7368f-cfb9-49a0-94ae-6cc0e5ead888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54d9f80b-8b40-46c0-8e1d-37be678aaf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    &lt;!-- HTML EMAIL BODY -->
                </value>
      <webElementGuid>461b7c07-ab2f-493e-8faa-a3505b0298b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html_msg_body&quot;)</value>
      <webElementGuid>eceffbdb-e0ce-48bf-9a95-c4eac449f305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='html_msg_body']</value>
      <webElementGuid>174a8306-e00d-400a-8506-4ebaf751c368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-html']/iframe</value>
      <webElementGuid>2bbb2d26-712d-4ee1-a106-9b70c2785f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTACHMENTS'])[1]/following::iframe[1]</value>
      <webElementGuid>6cb0839f-47b0-4a08-8fd1-23461f250faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMTP_LOG'])[1]/following::iframe[1]</value>
      <webElementGuid>6d195e8a-aa73-430e-892c-0ffba30c3d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click here'])[1]/preceding::iframe[2]</value>
      <webElementGuid>d6636e18-9bd8-4c88-b8cc-ab73ffd84c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://uat.saudiesports.sa//authnticate/dashboard'])[1]/preceding::iframe[2]</value>
      <webElementGuid>b6c9f329-7427-4724-8171-4f9a5003182f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;!-- HTML EMAIL BODY -->']/parent::*</value>
      <webElementGuid>c25dd00f-de35-43c9-871a-865bbe6b3adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>163231a0-939e-4e72-83de-f1dee4c280f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'html_msg_body' and @title = 'HTML Email Message Body' and @name = 'html_msg_body' and (text() = '
                    &lt;!-- HTML EMAIL BODY -->
                ' or . = '
                    &lt;!-- HTML EMAIL BODY -->
                ')]</value>
      <webElementGuid>2d0baf8f-3aab-467e-b7c0-43eead4c0119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
