<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>get invitation list</name>
   <tag></tag>
   <elementGuidId>b2307f7d-bc21-497b-bbb3-b39b2c43f2b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>b6c841ae-a234-473e-bcd0-f1b467f94d9a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9</value>
      <webElementGuid>413316fa-494e-40bb-af87-d3624ef0f1c3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5dzdmVHQzQTc3QmFLWjVTMlp4czNBeEZybEZ2a3JVNG1fMkI3WjQwX2s0In0.eyJleHAiOjE2ODg2Nzc0ODUsImlhdCI6MTY4ODY0ODY4NSwiYXV0aF90aW1lIjoxNjg4NjQ4NjY1LCJqdGkiOiIyM2Y3MTRiOS1hYjIyLTRlZmUtYTFhMS01NjU2MmU5MzJlMjYiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzNjkzZjA3NC0xODZhLTQ3YjUtYjE5Yi1mN2EzYWEyZjE3NzMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjQzMGIzY2M2LWQ5MWItNDhkZC04OGM4LTgxMDczNzJjODRkYSIsInNlc3Npb25fc3RhdGUiOiJhMGU0ZTVjZS01MTA3LTRkODMtYTFkOC0wMGY1NjBjZDMxZDgiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRFNfTyIsIkNfVF9BUl9PIiwib2ZmbGluZV9hY2Nlc3MiLCJDX1RfTVRBX08iLCJDX1RfRV9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiYTBlNGU1Y2UtNTEwNy00ZDgzLWExZDgtMDBmNTYwY2QzMWQ4IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiYXV0b21hdGlvbiBwbGF5ZXIgYWNjb3VudCIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1Nzc3Nzc3MDAiLCJnaXZlbl9uYW1lIjoiYXV0b21hdGlvbiBwbGF5ZXIgYWNjb3VudCIsInJpZCI6ImN1c3RfZXNwb3J0cy5jb20iLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYXV0b19wbGF5ZXJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.FRWCSC-qi4cxmQRExde9MbVivlkkLi05T1uL0o-Ht_AaMzI4Ei9hn-ij5QvY4z2XLkg129v41WsqRO84DeeCqp8RE7MmvWeDbssen9G9RlGRAFdTR34C_zsCJA44Y8H-6fcVwKYD28tbDMRGnNe7f_NeXhRAromrxK-r0gPL-ASmNtS7o1hRItm2vbGcsK5ympcOnGLMa_74pWg6cFAspeeinR09qR-HCrWsBmsKnk7Vgux0c4ClAlFu0Sf_3DnwNG8gDsxaUncAZKgemfleNIBeAdk29rR4rCEcwh_ccw9GUE6yf_4Dh8FTNUM-LtLzCX0Q5vGlkEAD9xdoi4y_-Q</value>
      <webElementGuid>25f9c96c-731b-41bd-9453-7a8b53688d61</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>02dc2f3e-f5c2-4711-9c3a-46fd01a21321</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>e332c755-5204-455f-a007-0a664742b6a4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/invitations/received</value>
      <webElementGuid>13552add-0878-4ba4-a383-497a86a46826</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>cf3f8db9-a3b1-4239-bf14-fa0332a28f76</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>a07c9da0-7bb8-4394-b341-41b375ac1b34</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>8ae2c3f5-bc6a-413d-a76f-8b6ef1fc41e0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36</value>
      <webElementGuid>c1527d81-49a2-43ec-912b-190e14374fb1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not.A/Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;114&quot;, &quot;Google Chrome&quot;;v=&quot;114&quot;</value>
      <webElementGuid>df71c45a-17ee-482d-a9bd-219cfa546151</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>3f9474bb-fca3-422d-8870-ed63e1f074e9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>9cf6bcd4-3820-45c6-9868-4438cf105e85</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/invitation?page=0&amp;size=10&amp;sort=creationDate,desc&amp;type=RECEIVED</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
