<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>get invitation by status</name>
   <tag></tag>
   <elementGuidId>c7e09a26-5ecd-4d66-a830-4054335adf26</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>a5ebb5ff-d44a-47db-a5af-fdabfb044bd1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>0f67055c-4df3-4ec6-80e7-446239841e44</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDAzODU1MjQsImlhdCI6MTcwMDM4MTkyNCwiYXV0aF90aW1lIjoxNzAwMzgxOTIzLCJqdGkiOiI4OTY1M2IyMi0wYjQ5LTQ0NzQtYmNhZi0wMzEyODlmMzk5NjEiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI5OWQwNWI1NS0yMTAyLTQ3NDEtYjA4My04NWQwNGM0ZjI3NTIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjNjMDFiOGZiLThjNzctNDI2Yi1hZGVjLTI0NjdjYzJhZDNkOSIsInNlc3Npb25fc3RhdGUiOiIwMmVkYTNlMS1lYzEzLTQ4NWItYTQwNy01N2ZhZjgwNjQ1MWYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX1RfRFNfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19DTF9WTVlfTyIsIkNfTUVfRFNfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19NRV9WQUxfTyIsIkNfQ0xfRFNfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiIwMmVkYTNlMS1lYzEzLTQ4NWItYTQwNy01N2ZhZjgwNjQ1MWYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJjb250ZW50IGNyZWF0b3IgYXV0b21hdGlvbiBhY2NvdW50IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiKzk2NjU4ODM5OTQ4OCIsImdpdmVuX25hbWUiOiJjb250ZW50IGNyZWF0b3IgYXV0b21hdGlvbiBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NvbnRlbnRAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.YX89BGhcXszEN05Gmw72FygJfNrVLmW6jxRBO6VvaKguQRd4Moztv9DJQJSXbMc6zymED-V0HUoHXVwCocME2LNUtIsT1bGnw6SYZyVmdG14FPDyXvbDbmIDybvvy3niCoZ_P5ZKZEkJZb5Y1j9nWP0ObK0Key0pfcNn5Hl-FYuYEwJDeWLbhZfj85XF6rxF3IKoiGk6oloDft3iS98URMvMQShQLSa52LNvnzyOd8K9bEgZQ1yKzcOLAuQiuHLaQvthhH_k03h6pZTxI6eAp0b8zMwKn3qFuFuoCGqRVAr356HwlbQvw-PbzNKaYJMbEbzT-re7a7qAokaX_dVmJg</value>
      <webElementGuid>5a9eb068-462b-45cd-9182-882f8a4453fb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>beb8d837-750a-47e0-9e2b-953b6abbf734</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>63f99852-f2fe-462d-a17d-f5ac242fa9a3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/invitations/received</value>
      <webElementGuid>b53b2f8e-da2f-4592-9470-8e3475657a6c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>ad319df6-a701-4e3a-a0c3-d8ed0b226d2e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>41ddf7f7-96c5-4bb5-8ba7-73e76161cebc</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>f5aea179-a08b-4409-9c86-bb4a226abf8e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36</value>
      <webElementGuid>a3308f1d-2796-4785-adf8-100d8f53000a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;119&quot;, &quot;Chromium&quot;;v=&quot;119&quot;, &quot;Not?A_Brand&quot;;v=&quot;24&quot;</value>
      <webElementGuid>534cc095-ab2c-42ad-9d22-34d9cecb6e67</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>f507abd1-fb46-4da0-8fb5-d4ab6d95bf8d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>8ccbd2ac-bc0e-401b-a8d0-b31e84faa09f</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/invitation?page=0&amp;size=10&amp;sort=creationDate,desc&amp;searchableValue=Pending&amp;type=RECEIVED</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
