<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>send invitation to content creator</name>
   <tag></tag>
   <elementGuidId>228258cb-682e-49c9-b69d-fe81470be7bc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;invType\&quot;: \&quot;CLUB_CONTENT_CREATOR\&quot;,\r\n    \&quot;invitationFrom\&quot;: \&quot;Club\&quot;,\r\n    \&quot;fromType\&quot;: \&quot;CLUB\&quot;,\r\n    \&quot;members\&quot;: [\r\n        {\r\n            \&quot;email\&quot;: \&quot;vvvvv@mailinator.com\&quot;,\r\n            \&quot;memberId\&quot;: null,\r\n            \&quot;role\&quot;: \&quot;CONTENT_CREATOR\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>3c5d3e9f-d690-4b79-bd00-8f1e98745aeb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>566746e2-e8e3-4508-8b08-3c1db452ea5c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDAzODY0NjYsImlhdCI6MTcwMDM4Mjg2NiwiYXV0aF90aW1lIjoxNzAwMzgyODY1LCJqdGkiOiI2MTdkMjRlYy03Yjg1LTRlZTEtODViOS0wMzhmMjhlNWRjYWIiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZWNhN2M4Zi0xYWFlLTRiZDAtOGFmYi00YmE0YmZhZGE3ZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjZkMDQ5MTZmLTFkMDYtNGRiZC05MDBiLTAxMmI5ZGI3NmI1OCIsInNlc3Npb25fc3RhdGUiOiI1YjRmNmZiMy1kZWYyLTQ0ODQtYjNmYS1iMjNhNzA2Y2RiNjIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfQ0xfVl9PIiwiQ19UX0FfTyIsIkNfQ0xfTVBfTyIsIkNfVF9VQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRVhQX08iLCJDX0NMX0VBTF9PIiwiQ19UX0VBTF9PIiwiQ19DTF9FTVlfTyIsIkNfVF9WX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfQ0xfQVNfTyIsIkNfTUVfRVhQX08iLCJDX0NMX1ZNWV9PIiwiQ19DTF9VQkxfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19UX1JDX08iLCJDX1RfTVRBX08iLCJDX0NMX0JMX08iLCJDX1RfRVhQX08iLCJDX01FX0VBUF9PIiwiQ19NRV9CTF9PIiwiQ19DTF9DQUxfTyIsIkNfVF9EU19PIiwiQ19DTF9NQV9PIiwiQ19NRV9VTkJfTyIsIkNfTUVfTUFfTyIsIkNfTUVfRFNfTyIsIkNfTUVfVkFMX08iLCJDX0NMX0RTX08iLCJDX1RfQVJMX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiNWI0ZjZmYjMtZGVmMi00NDg0LWIzZmEtYjIzYTcwNmNkYjYyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiQXV0b21hdGlvbiBDbHViIG93bmVyIGFjY291bnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTg4ODg4ODAwIiwiZ2l2ZW5fbmFtZSI6IkF1dG9tYXRpb24gQ2x1YiBvd25lciBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NsdWJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.c-64QpchYvn4ZFI6pik6aCA6HrHy1cK-hEnhHofA_aY3MQDAQ9bm0niku9XVgA8X5sUtkVMg11sBlnE5-gqd9lJR0xjw6t1a7fhkGVWh_kwfmUJ9hVq1YUvbHoJlUqf5pqvtZswaH9Fm9j0G-S6d7M4OhMLIrH1fyx70EDCZQlbpteGQ7kXhjDsyKVl0pIqxD1wFamYNGvh1GTq8vY-bhPzwdLOwK0xv6e-Oh_f4YhyUKXXfcDa9Kqr-gOsNuwXZOMgyjn4paPSnR2_GeEvxx77AmhhO2aPDPJRzuuAZCsvPZy6-A8IO_ARr7itfVfuq2F_VkRDtljWmZ9SvwKEWxg</value>
      <webElementGuid>fedfe5c2-8a03-497b-a5c3-a7c0e6080d32</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>37091a03-98a8-4888-9296-e33491f9b92d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>5dca314b-29c6-4e5b-9518-a5138330a0a1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>f8055c8a-ecef-42a7-85a5-4abe6058f473</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>e0ab5dc4-34bc-4706-b924-457662782e06</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/club/content-creators</value>
      <webElementGuid>c9cfd0e0-2840-4e1b-a782-7bd6fbb2a258</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>403deaaf-f7e2-4e7c-963e-d3575da5980f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>6b858eb9-aeb4-4f4a-9713-f7728312d385</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>1dcfb5fe-c37a-479c-b7f6-c7d3906b6117</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36</value>
      <webElementGuid>c9b7333b-56fd-47e2-9714-9bb5516604da</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;119&quot;, &quot;Chromium&quot;;v=&quot;119&quot;, &quot;Not?A_Brand&quot;;v=&quot;24&quot;</value>
      <webElementGuid>d535fd75-beaf-4921-a2f4-2a7c4272dfbf</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>3c97e9e8-0130-4918-9c91-36e09d3d08e4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>5f78faf1-3e88-4fc2-b80e-c4ac6bb57672</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/invitation</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
