<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>UpdateTeam</name>
   <tag></tag>
   <elementGuidId>610fe655-8312-4b2b-99c4-6e8b0dae9f3f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;name\&quot;: \&quot;AutoocZbRshWbmS\&quot;,\r\n    \&quot;nameAr\&quot;: \&quot;نادى ءجردزثآإسذ\&quot;,\r\n    \&quot;logo\&quot;: \&quot;esports/2d811920-bb6e-4f6b-9441-2ca6d90261ae__pngImage.png\&quot;,\r\n    \&quot;about\&quot;: \&quot;about EhTnqFeDQP\&quot;,\r\n    \&quot;publicProfile\&quot;: true,\r\n    \&quot;gameId\&quot;: 2,\r\n    \&quot;socialMedia\&quot;: [],\r\n    \&quot;invitations\&quot;: [\r\n        {\r\n            \&quot;email\&quot;: \&quot;Auto_content@mailinator.com\&quot;,\r\n            \&quot;role\&quot;: \&quot;CONTENT_CREATOR\&quot;\r\n        },\r\n        {\r\n            \&quot;email\&quot;: \&quot;Auto_blockplayer@mailinator.com\&quot;,\r\n            \&quot;role\&quot;: \&quot;PLAYER\&quot;\r\n        },\r\n        {\r\n            \&quot;email\&quot;: \&quot;Auto_blockplayer1@mailinator.com\&quot;,\r\n            \&quot;role\&quot;: \&quot;PLAYER\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>1ac8f117-8bd6-4981-9660-50f4e25bdf02</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>0b2255f4-c73e-48b9-95ed-1cc9a89cd5ca</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTg1ODQ4MDgsImlhdCI6MTY5ODU4MTIwOCwiYXV0aF90aW1lIjoxNjk4NTgxMjA2LCJqdGkiOiJkYWI5MzQ5OS05NzM3LTQ3N2YtOWNlOS1mNjAxOWE2Y2M4NzgiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJmZWNhN2M4Zi0xYWFlLTRiZDAtOGFmYi00YmE0YmZhZGE3ZTMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6ImNjNDE0ZDM3LTFhOWMtNGU0YS04NDAxLTY1ZTQ3MDhjMzIxZSIsInNlc3Npb25fc3RhdGUiOiI2YmZkYzZmMC1iYzg1LTQ4MTQtYjAwYi04N2Q3MTI4OTQwMDUiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfVF9VQVJfTyIsIkNfVF9BX08iLCJDX1RfRV9PIiwiQ19UX01UQV9PIiwiQ19UX0FSX08iLCJDX0NMX0VNWV9PIiwiQ19DTF9DQUxfTyIsIkNfVF9EU19PIiwib2ZmbGluZV9hY2Nlc3MiLCJDX0NMX01BX08iLCJDX0NMX0FTX08iLCJDX0NMX1ZNWV9PIiwiQ19NRV9EU19PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX0NMX0RTX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiNmJmZGM2ZjAtYmM4NS00ODE0LWIwMGItODdkNzEyODk0MDA1IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoiQXV0b21hdGlvbiBDbHViIG93bmVyIGFjY291bnQiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTg4ODg4ODAwIiwiZ2l2ZW5fbmFtZSI6IkF1dG9tYXRpb24gQ2x1YiBvd25lciBhY2NvdW50IiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhdXRvX2NsdWJAbWFpbGluYXRvci5jb20iLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.gfh3ZlDWoS3Vj-NrPtbm5pUMKqXryR_TBdk3PqsYF4SV2d8ofbx98O1EfBDwe5dwgDnTAjSbDaXNr6ZoXKyacd4DfG6QlESLFs-48EaOlG1e838GX9XetB22HY-dZSSbTD_lEqgR5w6WR1y7JsA2WBuUhFwQMBbaDQMiPIOcaBUS_SiqchDdim8XaXawNMfnViXpOd0vskgqKEw_LKRAPQ457yGN9BhwBAIikITcP7cve6eqgX2OPi4KOyY1mxRs4of6AlpIl2LWNnqmDOZVFVQzEda3aOH9i249hsUcmX3V1RfHWPPPshIptxFQvSdlnZT-Qdcx0EI8H75gwMI27Q</value>
      <webElementGuid>b38da36e-2818-434b-a3b4-e5a8e23ffd60</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>d768828c-2084-40ae-8d45-8e8e6d5b57ac</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>36733404-e8cc-47c9-b4c2-4f1b6b7055b6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>a0daf2de-f3c0-4a9f-b660-5e33edd63a7b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>c09f08fe-5e5f-464e-ad35-2f0410aefa87</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/teams/edit/61f07430-538c-4c83-bf36-2104614e5603</value>
      <webElementGuid>380ea49c-5387-4a66-a65d-29d44d96b6e7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>e97e2a08-8d0e-461f-b8ff-e340c88e377b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>ed3c54f5-a456-4ff5-a93e-5176a43b13ff</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>46ef1453-0222-47ca-892f-281a96ce7340</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36</value>
      <webElementGuid>c9a1beef-68b5-4e97-9370-1cb527d326ad</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;118&quot;, &quot;Google Chrome&quot;;v=&quot;118&quot;, &quot;Not=A?Brand&quot;;v=&quot;99&quot;</value>
      <webElementGuid>b72db5ad-5e89-41c8-b32e-08720738bec0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>000126bb-14ef-4ce7-9673-949c87e79dba</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>77f36fb3-8beb-42cc-8a56-8f604f058f23</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/teams/61f07430-538c-4c83-bf36-2104614e5603</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
