<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Block member</name>
   <tag></tag>
   <elementGuidId>9cd536a6-47b6-44d7-9036-0f3f2254ff5c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\&quot;lockReason\&quot;:\&quot;test\&quot;,\&quot;userId\&quot;:\&quot;d452a305-9b41-4ff5-bfbe-5a8e413ba852\&quot;}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>a2bdf487-3d81-4315-8d05-7d6020dea584</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-US,en;q=0.9,ar;q=0.8</value>
      <webElementGuid>7417545c-f27e-4740-b44a-c40037bcfef8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJma1JPclNrWFZZT3FSTFl2UnNOUXdiZHFuTmoxQk1JSHMtNkVsUl9ybEswIn0.eyJleHAiOjE2OTY4NTI3MzEsImlhdCI6MTY5Njg0OTEzMSwiYXV0aF90aW1lIjoxNjk2ODQ5MTI5LCJqdGkiOiJkZWNiYWY2ZS02MGVjLTQzYjgtODY0OS05N2Y0ZmE2NTFmMGQiLCJpc3MiOiJodHRwczovL3FhLnNhdWRpZXNwb3J0cy5zYS9hdXRoL3JlYWxtcy9jdXN0X2VzcG9ydHMuY29tIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImZiOTRmZTY3LTMxOWMtNDIyYi04NTgzLWEzZTU4NzhlMDY4NCIsInR5cCI6IkJlYXJlciIsImF6cCI6IldFQiIsIm5vbmNlIjoiYzU3MDNhMTMtZDE1Mi00ZmM4LTkyOGYtNDJlMzU1MDZiOGIyIiwic2Vzc2lvbl9zdGF0ZSI6IjZmODI0OWMwLTFhM2QtNDI2Zi1hYmE1LTZjZWVjNjg1ZWVmMiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiQ19VUF9WX08iLCJDX1JfVkFTX08iLCJDX1RfVUFSX08iLCJDX1VfQkxfTyIsIkNfQ0xfTVBfTyIsIkNfVF9VQUxfTyIsIkNfUl9TRF9PIiwiQ19PX0VfTyIsIkNfVVBfRF9PIiwiQ19UQ19FX08iLCJDX0NMX0VNWV9PIiwiQ19DUlFfRV9PIiwiQ19UX1ZfTyIsIkNfQ0xfVk1ZX08iLCJ1bWFfYXV0aG9yaXphdGlvbiIsIkNfVV9SU01fTyIsIkNfVF9NVEFfTyIsIkNfTUVfQkxfTyIsIkNfVF9EU19PIiwiQ19DTF9NQV9PIiwiQ19NRV9VTkJfTyIsIkNfTUVfRFNfTyIsImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfQUxfRVhQX08iLCJDX0NMX1ZfTyIsIkNfVF9BX08iLCJDX1JfVkFMX08iLCJDX1RfQVJfTyIsIkNfVF9FX08iLCJDX0NMX0VYUF9PIiwiQ19DTF9FQUxfTyIsIkNfVF9FQUxfTyIsIkNfVVBfRV9PIiwiQ19VUF9BX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfQ0xfQVNfTyIsIkNfVV9FX08iLCJDX01FX0VYUF9PIiwiQ19SU19FX08iLCJDX1VfVUJMX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9FWFBfTyIsIkNfQ0xfQkxfTyIsIkNfTUVfRUFQX08iLCJDX0NMX0NBTF9PIiwiQ19VX1ZfTyIsIkNfTUVfTUFfTyIsIkNfTUVfVkFMX08iLCJDX0NMX0RTX08iLCJDX1RfQVJMX08iLCJDX05SX0VfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiI2ZjgyNDljMC0xYTNkLTQyNmYtYWJhNS02Y2VlYzY4NWVlZjIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6IjNiNmZhNmMzLTU3MzQtNDI1ZC1iMWIyLWExMjQ3YjViNjc2YyIsIm5hbWUiOiLYs9mE2YjZiiDYp9mG2KrYsdmG2KfZhCIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTY2NjcwMDAiLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZ2l2ZW5fbmFtZSI6Itiz2YTZiNmKINin2YbYqtix2YbYp9mEIiwiZW1haWwiOiJzYWx3YWludGVybmFsQG1haWxpbmF0b3IuY29tIiwia2V5IjoiY3VzdF9lc3BvcnRzLmNvbV9LRVkiLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.Owz9ABGuxdbkQgJfwDFkgbqMsc5T8WPBMhu9VHXjXk-AkLqgobd_4mo5T6WOQR1nz10OGBE6ZgaDg3eOCvpCiZbpipN8_2xUJSiEMN-z4rkKJc3bpKMazsz1M_7uqAwjB762NNbtRVaYd8M6f6k6YwQK3CtzWaz0rYDEQ3ZytoNcy3qk4EEv2bgZfg88xA81VYwbREH7Vw-YcbDCh81Nfhe_0qcV4bDQrg-ecu568DxSKbu-w6IIwdxP0v8cLZ1QPiuGewrEeoWEocO7IbdZfLULBvEPZAneM3H9GadHfsvfq97xfXVQfzbslpBVRGOGWKcA1F3O-g0m2GJoHB0beQ</value>
      <webElementGuid>5dfb4acd-c541-4f41-8495-7a06a1b40490</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>6083179c-faeb-45b1-b69c-d6b2ed059f52</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>6152c25b-e89d-4fd5-83d8-ef4c6a202f09</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Cookie</name>
      <type>Main</type>
      <value>_ga=GA1.2.136443116.1689761754; _ga_SB6CJ3T42M=GS1.1.1692194498.4.1.1692195011.0.0.0; _ga_62ZJM7QNXP=GS1.1.1692194499.4.1.1692195011.0.0.0</value>
      <webElementGuid>4dad6708-636e-4325-992b-35a8cab81ea6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>3f7bec80-36eb-4c58-88ff-a60e1ef41889</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://qa.saudiesports.sa</value>
      <webElementGuid>cdfb5394-93f0-4a77-9205-9b4ae149666d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://qa.saudiesports.sa/authnticate/admin-members/all-members/view/e41cbe51-3dc3-452c-a71a-92f9ac6d9f91</value>
      <webElementGuid>6ab47418-d3df-440b-b73b-da295959ccf1</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>5de41503-0271-45be-b463-54ea6eded204</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>6f5fc6bf-f768-4b46-88a8-284f7ea5b43f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>a82a849f-c30d-4ed9-bd63-ce2c5065b713</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36</value>
      <webElementGuid>a9fa2023-0ada-42b5-b60e-4324b190469e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Google Chrome&quot;;v=&quot;117&quot;, &quot;Not;A=Brand&quot;;v=&quot;8&quot;, &quot;Chromium&quot;;v=&quot;117&quot;</value>
      <webElementGuid>2115721c-cdaa-4348-ad77-2b8c452b5d15</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>bc0cf570-cd59-4e2e-ac24-6e7c924d88b9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>b8ce4e45-6b03-4259-97c2-f74e78afa5c2</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/members/block</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
