<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>filterMember</name>
   <tag></tag>
   <elementGuidId>c6b28048-8f3e-49ed-92e2-b14f6d1104de</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;filters\&quot;: [\r\n        {\r\n            \&quot;columnName\&quot;: \&quot;query\&quot;,\r\n            \&quot;columnValue\&quot;: \&quot;Auto_blockplayer@mailinator.com\&quot;,\r\n            \&quot;columnValues\&quot;: [],\r\n            \&quot;operator\&quot;: \&quot;equals\&quot;\r\n        }\r\n    ],\r\n    \&quot;pageNo\&quot;: 0,\r\n    \&quot;pageLength\&quot;: 10,\r\n    \&quot;sorting\&quot;: [\r\n        {\r\n            \&quot;sortName\&quot;: \&quot;id\&quot;,\r\n            \&quot;sortType\&quot;: \&quot;DESC\&quot;,\r\n            \&quot;sortColumnType\&quot;: \&quot;string\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>467b18ff-f1ee-40ba-993f-49874b750ca8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>e8336fe2-5d13-429e-8865-55411fd83248</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE2OTg1ODIwNTYsImlhdCI6MTY5ODU3ODQ1NiwiYXV0aF90aW1lIjoxNjk4NTc4NDU1LCJqdGkiOiJmMDQ2NzRiNS1lNDI4LTRkNTYtOTdhZi05MjRmOThhYTQzMzAiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6ImRiODJiYTg2LTEyMWMtNDg2Ni04YzdlLWYxNGVjZjFhZDJkMiIsInNlc3Npb25fc3RhdGUiOiIxYjBlYWY2Ny0wZTg3LTQ0NTUtODVmNC04MDIwOTg3YzM1YTEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX1VQX0RfTyIsIkNfVENfRV9PIiwiQ19DTF9FTVlfTyIsIkNfQ1JRX0VfTyIsIkNfVF9WX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX1RXX0VfTyIsIkNfTUVfVU5CX08iLCJDX01FX0RTX08iLCJkZWZhdWx0LXJvbGVzLWN1c3RfZXNwb3J0cy5jb20iLCJDX0FMX0VYUF9PIiwiQ19DTF9WX08iLCJDX1RfQV9PIiwiQ19SX1ZBTF9PIiwiQ19UX0VfTyIsIkNfVF9BUl9PIiwiQ19DTF9FQUxfTyIsIkNfQ0xfRVhQX08iLCJDX1RfRUFMX08iLCJDX1VQX0VfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19VUF9BX08iLCJDX0NMX0FTX08iLCJDX1VfRV9PIiwiQ19PX1ZfTyIsIkNfUlNfRV9PIiwiQ19VX1VCTF9PIiwiRVNQT1JUIiwiQ19NRV9FWFBfTyIsIkNfQ0xfVUJMX08iLCJDX1VfRVhQX08iLCJDX1VfQV9PIiwiQ19SX1JBU19PIiwiQ19UX1JDX08iLCJDX1RfRVhQX08iLCJDX0NMX0JMX08iLCJDX01FX0VBUF9PIiwiQ19DTF9DQUxfTyIsIkNfVV9WX08iLCJDX01FX01BX08iLCJDX0FSQ19FX08iLCJDX01FX1ZBTF9PIiwiQ19DTF9EU19PIiwiQ19OUl9FX08iLCJDX1RfQVJMX08iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiMWIwZWFmNjctMGU4Ny00NDU1LTg1ZjQtODAyMDk4N2MzNWExIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInVsaWQiOiJmOTRlMDI1MS02MmQxLTRhYTQtYmM1NS1jNDMzNGQzZmExMTQiLCJuYW1lIjoic3VwZXIgYWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiIrOTY2NTU0MjU0MjMyIiwiZ2l2ZW5fbmFtZSI6InN1cGVyIGFkbWluIiwicmlkIjoiY3VzdF9lc3BvcnRzLmNvbSIsImZhbWlseV9uYW1lIjoiIiwia2V5IjoiY3VzdF9lc3BvcnRzLmNvbV9LRVkiLCJlbWFpbCI6ImFkbWluQHNhdWRpZXNwb3J0cy5zYSIsImNpZCI6IjFfU1RDU19DVVNUIn0.o0Bo_YlGZeYN29IBaTID6TeZGBOkyaz3ZQJ8zIw347tQzmAeYRvSVn7bKu0vhsosTrwhcjYsbgonAbOFaltlB6LuT46k_Y42JV3wsXgWGCtS1XO-ewMS9QEMIf-VMUh38ZtmvdFw7IEsctbiRHMhhPDYlKUValDd-emSbP2s7W7OygJrzJFSPX6bEsCeE2PjLT5VHg2SfF4tK4-crcvhtMs5kVe7sngBRdi8cNuHxqbgJlgTSJ5KhM5wAq-oQlaSPFGi5nkJEZ5oE4zU9iOEH2MuhAQMxwSolOfgrCnzmVAugqfW_F073swBmlu2wusOEMRKl0Jx74tqP6wgZMVfPg</value>
      <webElementGuid>60ced6d2-9aad-486e-83b3-7aa85a1238f3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>3aedfed7-4784-41d9-8415-f86fa6fa29a6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ae1776f1-dca0-4070-8f68-4cb0dcfe236e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>4ab60384-c033-45c8-b2f9-1da18a91c69e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>719b1b55-3d44-40f1-8cbe-d21e43153f03</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/admin-members/all-members</value>
      <webElementGuid>0f0cfd5b-1b5e-445a-84ef-4c1a331786eb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>81d08018-f83c-403b-addf-d531737e310a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>4ba6ebf5-dc7c-4ca1-8f11-6174f180d085</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>bd946957-22d1-446d-bfe0-3ec50b982370</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36</value>
      <webElementGuid>c5972d44-6728-4234-9397-939bdf4818b4</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;118&quot;, &quot;Google Chrome&quot;;v=&quot;118&quot;, &quot;Not=A?Brand&quot;;v=&quot;99&quot;</value>
      <webElementGuid>82007c6a-0492-49c5-a1fa-1a32d749fac2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>083e30f2-97a5-4b12-ab7d-48a0af95d611</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>e791d51c-f278-42bd-8477-2f3f1f47a2df</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/members</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
