<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__new-clubIban</name>
   <tag></tag>
   <elementGuidId>e1363101-b9a2-41d3-b64a-dbcefa3a4df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new-clubIban</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-clubIban']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;SA0380000000608010167519&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb8a2544-ce1f-4b69-8a82-7a896c4299a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54925f6f-1c12-478e-9337-db3a427c740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-clubIban</value>
      <webElementGuid>f0c9cfb2-f4fb-4987-b1a7-7e174198145c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-clubIban</value>
      <webElementGuid>3f712cdc-cfd3-4efe-b2db-1bbb629ab127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clubIBAN</value>
      <webElementGuid>bb4397cc-8ebf-4c1e-b6df-de5269e288ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f5803bfd-1b2d-4fe4-beb9-f82cace27e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SA0380000000608010167519</value>
      <webElementGuid>b8afebe3-9a74-4681-936d-d1c39f2e9949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-clubIban&quot;)</value>
      <webElementGuid>ca15bdd6-35be-40db-bfe6-73d3585bb30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-clubIban']</value>
      <webElementGuid>5a29f379-2e1f-4c27-8d1b-2bfc3d11de9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c72db2c8-3cd7-447a-b2b3-6bfc032a5381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'new-clubIban' and @placeholder = 'SA0380000000608010167519']</value>
      <webElementGuid>d11f98cb-a6ff-43c1-b00e-9a40c04653e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
