<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__clubNameAr</name>
   <tag></tag>
   <elementGuidId>5af73580-6a89-43e8-957a-b92ca8faf7c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clubNameAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clubNameAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Club Name (Ar)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdc93211-21b6-4367-b72c-69e4fdd2fb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>745ddffb-f1a3-4af6-9c08-02ffdb92606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b01fea3a-732d-4f25-9066-322f2fffca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clubNameAr</value>
      <webElementGuid>876b5bbf-d266-4f01-89c0-97b1812fcd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clubNameAr</value>
      <webElementGuid>027a6a0e-1953-458c-b43d-0ed98d818ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>56990fdc-7938-4c1f-82f4-b50c43e33cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Club Name (Ar)</value>
      <webElementGuid>fbe586b8-e5e2-41e7-bcee-80652ccb21b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clubNameAr&quot;)</value>
      <webElementGuid>b0798aee-ba11-4aba-9d5a-7ebfaf2ca5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clubNameAr']</value>
      <webElementGuid>6cbb7fd4-ab30-4396-9426-e01cc1ced7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3677a23b-a96a-4815-9159-da4ae08feb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'clubNameAr' and @placeholder = 'Club Name (Ar)']</value>
      <webElementGuid>4dbe0e5a-d007-407f-9349-fcd708db7c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
