<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__new-nationalId</name>
   <tag></tag>
   <elementGuidId>df19ef8a-d21d-492d-b42d-6428ed937c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new-nationalId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-nationalId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ex: 1998463&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0393aa02-d610-4ccd-9859-7ca538c77b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6eb14e31-fb25-4872-ad3e-3f1a4b40fe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-nationalId</value>
      <webElementGuid>6c53ac16-d793-43f2-9f19-d8eb0ed5af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-nationalId</value>
      <webElementGuid>9f737fb8-c4d1-4303-b60a-98e6f7650cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nationalId</value>
      <webElementGuid>d474784a-cc9e-44a0-9cd7-9ebefac2471a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 1998463</value>
      <webElementGuid>a312b5fd-5b70-44ce-97ef-b5baaa6be7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d68ca384-652a-43cc-95a7-52977cec868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-nationalId&quot;)</value>
      <webElementGuid>0d6fa3b3-d031-4a7b-aed6-368623fb0143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-nationalId']</value>
      <webElementGuid>378834a8-3088-476a-9d83-16a1a29146f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div[2]/div/input</value>
      <webElementGuid>df0ae2fa-e429-473e-8553-5ddd3a847fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'new-nationalId' and @placeholder = 'Ex: 1998463']</value>
      <webElementGuid>ace071e1-dd4d-48ee-b3bd-f580da910fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
