<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Saudi</name>
   <tag></tag>
   <elementGuidId>689b4591-37f6-4d3d-8f85-60fa2d1ee3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Guinea-Bissauan'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a3748ac815a7-147</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Saudi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9357123f-98c1-4a5f-bac7-7521d643f68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>f9c44490-672d-42dd-8a23-3f02e8e96362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>524134c6-30c4-4343-8c27-bf8da74ffe41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a3748ac815a7-147</value>
      <webElementGuid>c99fd443-70f6-41b5-8551-25d3b357058b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Saudi </value>
      <webElementGuid>ac14ac9e-4765-4a58-9555-eba03c7806b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3748ac815a7-147&quot;)</value>
      <webElementGuid>6312a6c4-71e4-49e1-a1cf-4b00487f99b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a3748ac815a7-147']</value>
      <webElementGuid>924fdd01-183f-44e8-b49d-f3b4db601447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a3748ac815a7']/div/div[2]/div[2]</value>
      <webElementGuid>aa09432a-b9df-435d-ac86-173562f8ca33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guinea-Bissauan'])[1]/following::div[1]</value>
      <webElementGuid>df66002d-0f97-4bda-867c-548353018788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose Nationality'])[1]/following::div[6]</value>
      <webElementGuid>ea97a53e-4900-47b1-808e-b697307fb016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of birth'])[1]/preceding::div[1]</value>
      <webElementGuid>ec6b8cd5-53a7-40a0-9649-2e5591d1352a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>ec27c0f5-2084-4ca5-9006-1a0e58e9b781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a3748ac815a7-147' and (text() = ' Saudi ' or . = ' Saudi ')]</value>
      <webElementGuid>ec7fef62-e2a1-46fc-b7e9-707b4e55c2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
