<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Guest</name>
   <tag></tag>
   <elementGuidId>b847871e-ebde-4cf2-8711-ea60f6ba507b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ae0bb9886695-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ae0bb9886695-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Guest&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60988d72-3512-49a3-bde8-043f9a74f1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>5061fd36-7e00-4dd9-9de3-7a72c881bd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d3049710-4ebc-4da9-b72d-bc6ec64eccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ae0bb9886695-1</value>
      <webElementGuid>60ed08da-e382-4b91-bed9-eeaf9f2abe92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Guest </value>
      <webElementGuid>5cd7a19d-de9b-4c90-9556-782ba8b6c75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ae0bb9886695-1&quot;)</value>
      <webElementGuid>8aeaa6cb-beb6-4008-8c23-65399bebdd8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ae0bb9886695-1']</value>
      <webElementGuid>d82e4737-d2c6-48d5-bcc9-22e3e91ea24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ae0bb9886695']/div/div[2]/div[2]</value>
      <webElementGuid>039e269d-e604-47e4-8a07-b3f391727891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your role'])[3]/following::div[1]</value>
      <webElementGuid>c46a925e-3868-464d-92da-62112d8f9774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your role'])[2]/following::div[6]</value>
      <webElementGuid>fd70dbcd-9782-4ac2-ae4c-ea572d44e1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Player'])[1]/preceding::div[1]</value>
      <webElementGuid>bad07971-c319-4882-9827-6878dad9293a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>87cf34d6-23a0-45b1-b7e9-56f0c42a6162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ae0bb9886695-1' and (text() = ' Guest ' or . = ' Guest ')]</value>
      <webElementGuid>cbe02f1d-2f23-473a-b234-ff336a0b3885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
