<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Content Creator</name>
   <tag></tag>
   <elementGuidId>df8fecbd-b384-4aa3-888b-3eb9c67f4204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a745e9aa6cdd-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add member email address or ID'])[1]/preceding::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Content Creator&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>852c57f1-bc9f-4f03-b4c6-4e97f20b7e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>50a44276-336a-437f-895e-61c7a9fd3017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f97ed85e-a865-4947-a0b0-a7ddef46d2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a745e9aa6cdd-9</value>
      <webElementGuid>dc7b3f30-0658-4b7f-a63d-74ea1e3fab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Content Creator</value>
      <webElementGuid>0be25be0-1269-4aa0-8453-ba174f041889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a745e9aa6cdd-9&quot;)</value>
      <webElementGuid>3287c26b-cd96-4287-9ff8-9e43d5ef00d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a745e9aa6cdd-9']</value>
      <webElementGuid>9288f42b-8d25-4276-ac03-1760b6e1b274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a745e9aa6cdd']/div/div[2]/div[10]</value>
      <webElementGuid>4ac1d60d-78b7-4ebb-8344-c49f18f14d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Streamer test'])[1]/following::div[1]</value>
      <webElementGuid>52bc7a36-f357-411e-9c5f-19927c92dc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Graphic Designer'])[1]/following::div[2]</value>
      <webElementGuid>8644975a-e111-4a79-9bfb-107e517415a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add member email address or ID'])[1]/preceding::div[1]</value>
      <webElementGuid>5bc7b5dc-b9e9-4793-a8b5-4fd1f453b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>26dc96b1-8160-4645-897d-319219e9c3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a745e9aa6cdd-9' and (text() = 'Content Creator' or . = 'Content Creator')]</value>
      <webElementGuid>58fda365-6789-4577-8280-242bdefb1812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
