<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Referee</name>
   <tag></tag>
   <elementGuidId>c75a0a1a-37e9-490a-8dda-655eefa428a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aca9bc44e0fa-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aca9bc44e0fa-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Referee&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25e5712c-656a-48c4-97f1-8270bd03eeea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>20105bfa-f460-41f0-862e-20aec9a4ffb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9f3a5877-72a2-4e00-9ffb-d7f9b69fa695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aca9bc44e0fa-3</value>
      <webElementGuid>9eb34b1e-bb51-4f35-80a5-d6a3c2290828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Referee </value>
      <webElementGuid>47d589e5-d5f1-4aad-ba39-78d9bcbb2cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aca9bc44e0fa-3&quot;)</value>
      <webElementGuid>7cc97f0a-6bc5-45ef-9be7-248467af560e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aca9bc44e0fa-3']</value>
      <webElementGuid>15fab9ca-f5a5-41f1-8a62-9fd4f632e990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aca9bc44e0fa']/div/div[2]/div[4]</value>
      <webElementGuid>c3e0f959-58cd-4070-9253-323e85e27e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Player'])[1]/following::div[1]</value>
      <webElementGuid>c9ecac57-73f3-4040-aeb3-5cdec7c19c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest'])[1]/following::div[2]</value>
      <webElementGuid>4320ba4d-ae18-4dd4-bf11-ae2e4c809125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coach'])[1]/preceding::div[1]</value>
      <webElementGuid>4e983d20-a1f7-427c-97dd-b81aa33191c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>44ae0444-c2bf-4b01-b3a7-3109ceba3b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aca9bc44e0fa-3' and (text() = ' Referee ' or . = ' Referee ')]</value>
      <webElementGuid>3f61ee83-3f94-4bfc-90cf-d32e2fe9c94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
