<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon</name>
   <tag></tag>
   <elementGuidId>b2de3a1d-5f31-4b85-866b-fc3a4e94ff7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>polygon</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Choose month and year&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
      <webElementGuid>14c35aae-1ab8-4e40-a7f3-7091a045749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>0,0 5,5 10,0</value>
      <webElementGuid>a3a9b462-f870-4089-9ac5-baf0a9b61360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-datepicker-0&quot;)/mat-calendar-header[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-calendar-header&quot;]/div[@class=&quot;mat-calendar-controls&quot;]/button[@class=&quot;mat-focus-indicator mat-calendar-period-button mat-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/svg[@class=&quot;mat-calendar-arrow&quot;]/polygon[1]</value>
      <webElementGuid>804ca4a5-55b1-426a-9412-8b1b5f82aca1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
