<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>role_option</name>
   <tag></tag>
   <elementGuidId>eff940ad-c14a-4291-ad14-c4315ca7340f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your role'])[3]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ae0bb9886695-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ae0bb9886695-1' and (text() = ' Tournament Organizer ' or . = ' Tournament Organizer ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;${role}&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4e4f4de-b6ce-4780-8564-4defe4ecfa7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>b03c97ea-1007-407a-b77d-27a6fb1b14ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>22318636-14b5-42d7-aae4-2d7c98ecfb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ae0bb9886695-1</value>
      <webElementGuid>8c3fb16b-65ea-4df9-967c-5446bcc00178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tournament Organizer </value>
      <webElementGuid>7b489d7f-d339-4c77-92e8-bf039e212050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ae0bb9886695-1&quot;)</value>
      <webElementGuid>f1e64822-f820-4066-8834-d0f6bbef17ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ae0bb9886695-1']</value>
      <webElementGuid>a3c8e63d-27cd-4c4d-8fdf-afe021b15be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ae0bb9886695']/div/div[2]/div[2]</value>
      <webElementGuid>2aac8165-87de-45f1-9c44-81efa4e8fff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your role'])[3]/following::div[1]</value>
      <webElementGuid>f2b266b0-8eba-4171-ad3a-812fff188b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your role'])[2]/following::div[6]</value>
      <webElementGuid>4386e716-aac8-4c1b-8e4e-dce30e20d402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Club Owner'])[1]/preceding::div[1]</value>
      <webElementGuid>14521c32-3ffb-4be6-851d-dcbc10240667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>a6968824-b586-4e71-9e55-78f6a78f9e28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
