<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Auto_contentmailinator.com</name>
   <tag></tag>
   <elementGuidId>6802f041-30b3-4d21-9dbe-170650405b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-clan-members-modal/form/div[2]/div[3]/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Auto_content@mailinator.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c5b600b-b3c8-45ab-87e3-6309a4d25680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>fd225835-75d1-4121-94d6-ea3924d63c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Auto_content@mailinator.com </value>
      <webElementGuid>e95aa1b9-0774-42e2-98f0-47c52d613411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-clan-members-modal[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-touched ng-dirty ng-submitted ng-invalid&quot;]/div[@class=&quot;mat-dialog-content&quot;]/div[@class=&quot;form-group mb-0&quot;]/div[@class=&quot;email-chips d-flex justify-content-start align-items-center flex-wrap ng-star-inserted&quot;]/div[@class=&quot;email-chip d-flex justify-content-center align-items-start ng-star-inserted&quot;]/div[@class=&quot;chip-text d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;chip-content d-flex justify-content-start align-items-center flex-wrap&quot;]/span[@class=&quot;mail&quot;]</value>
      <webElementGuid>d3c8656e-c890-4d93-844e-8d8f814575c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-clan-members-modal/form/div[2]/div[3]/div/div/div/div/span</value>
      <webElementGuid>3b911e4c-7081-4b7e-94ac-d47ce2690713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invitation list'])[1]/following::span[1]</value>
      <webElementGuid>4292cde8-a4e8-4c0a-a260-5ea14cede772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::span[3]</value>
      <webElementGuid>b0e28195-4595-4ff0-bbcb-6d92cefdd66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content Creator'])[2]/preceding::span[1]</value>
      <webElementGuid>1b0e62d4-1982-45eb-943c-86b4b76a0855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::span[5]</value>
      <webElementGuid>5336b23d-f358-4fdb-bba3-db291dd168ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Auto_content@mailinator.com']/parent::*</value>
      <webElementGuid>191c9ea1-bc7b-4457-a965-19304d69cff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/span</value>
      <webElementGuid>0c692ecd-bd5f-4169-b8d1-1971d3883c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Auto_content@mailinator.com ' or . = ' Auto_content@mailinator.com ')]</value>
      <webElementGuid>45db0e60-55bc-477c-8e75-4ca2052759bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
