<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clan Name AR_clanNameAr</name>
   <tag></tag>
   <elementGuidId>c9a7fe4f-f868-45c0-a6c3-607f7d29b2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clanNameAr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clanNameAr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Clan Name AR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4ae75ad-acec-42ec-a543-6fd72d1a0b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clanNameAr</value>
      <webElementGuid>8cde8387-2fb8-47d9-89bd-4b7334e9b7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f6830ce-f0c8-48f7-a29a-7deac113793b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fba4c164-ab7f-4290-a5f4-32a22b040200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>nameAr</value>
      <webElementGuid>4355fa64-c388-4ceb-a9b6-c2d64ff198bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0eb33d3b-3c3b-4fb9-b537-fdc1ee35f4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Clan Name AR</value>
      <webElementGuid>45257d63-ff30-4df7-934d-be870d3c6872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clanNameAr&quot;)</value>
      <webElementGuid>f4e9e009-1e09-4cf5-80ef-3b9d567dacf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clanNameAr']</value>
      <webElementGuid>f0f1325e-2f14-4980-b9de-2628140d7a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>483793d6-48d6-470c-a1d2-d7450e2829d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clanNameAr' and @type = 'text' and @placeholder = 'Clan Name AR']</value>
      <webElementGuid>fff365b4-4912-4363-bd69-728b0c611a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
