<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>filter request by status</name>
   <tag></tag>
   <elementGuidId>b8de6883-59af-4f74-bf9b-3d4a26dbe283</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;filters\&quot;: [\r\n        {\r\n            \&quot;columnName\&quot;: \&quot;name\&quot;,\r\n            \&quot;columnValue\&quot;: \&quot;Approved\&quot;,\r\n            \&quot;columnValues\&quot;: [],\r\n            \&quot;operator\&quot;: \&quot;equals\&quot;\r\n        }\r\n    ],\r\n    \&quot;pageNo\&quot;: 0,\r\n    \&quot;pageLength\&quot;: 10,\r\n    \&quot;sorting\&quot;: [\r\n        {\r\n            \&quot;sortName\&quot;: \&quot;createdAt\&quot;,\r\n            \&quot;sortType\&quot;: \&quot;DESC\&quot;,\r\n            \&quot;sortColumnType\&quot;: \&quot;date\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authority</name>
      <type>Main</type>
      <value>stage.saudiesports.sa</value>
      <webElementGuid>b3df8e31-c29b-49fc-891c-43958ba69bb9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>a618d638-2a94-4970-a325-95ac722c3b05</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>eeb564c9-0496-4009-aa6e-201e3e006991</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5dzdmVHQzQTc3QmFLWjVTMlp4czNBeEZybEZ2a3JVNG1fMkI3WjQwX2s0In0.eyJleHAiOjE2Nzc1OTQzNTQsImlhdCI6MTY3NzU5MDc1NCwiYXV0aF90aW1lIjoxNjc3NTkwNzUyLCJqdGkiOiI2OTFhZTMwYy1mMGQ5LTQ2MjktYWFkZi03ZDViMGY4YWJkYTAiLCJpc3MiOiJodHRwczovL3N0YWdlLnNhdWRpZXNwb3J0cy5zYS9hdXRoL3JlYWxtcy9jdXN0X2VzcG9ydHMuY29tIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjU3ZmJjNWQ4LWZkMzUtNGY3MC05MTA4LTk0Mjc5Nzc3MmUxOCIsInR5cCI6IkJlYXJlciIsImF6cCI6IldFQiIsIm5vbmNlIjoiNDI4NWU5NWYtZTIyYy00NmQzLTk0YTktZDIwNjZlMGE1ZWY3Iiwic2Vzc2lvbl9zdGF0ZSI6IjhhYTlmMDUzLTlmMDItNGZlNC05NGY5LThhNzZlNjVhNDI4ZSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1jdXN0X2VzcG9ydHMuY29tIiwiQ19VUF9WX08iLCJDX1JfVkFTX08iLCJDX1VfQkxfTyIsIkNfUl9WQUxfTyIsIkNfVV9SU01fTyIsIkNfUl9TRF9PIiwiQ19PX0VfTyIsIkNfVVBfRF9PIiwiQ19VUF9FX08iLCJDX1VQX0FfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19VX1ZfTyIsIkNfVV9FX08iLCJDX09fVl9PIiwiQ19VX0RfTyIsIkNfUlNfRV9PIiwiQ19VX1VCTF9PIiwiRVNQT1JUIiwiQ19VX0VYUF9PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX1VfQV9PIiwiQ19SX1JBU19PIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjhhYTlmMDUzLTlmMDItNGZlNC05NGY5LThhNzZlNjVhNDI4ZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW5AZXNwb3J0cy5zYSIsImdpdmVuX25hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwibG9jYWxlIjoiZW4iLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZmFtaWx5X25hbWUiOiIiLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYWRtaW5AZXNwb3J0cy5zYSIsImNpZCI6IjFfU1RDU19DVVNUIn0.ZCwu76ewqSMaBtQFi1QJNtDkw-ZUVTOPevcoOz47iv6l6Phk08ogqQBc8SgJkk0miez_YizENB_ztPDtbGU5_8IQVrlnC7PoRJ_bPkVMP2ria2TwiWqgx5JowJFa8wDjJsuHawxmUS6dGT14925L8LdSvS2L86idIh_ahaFsdJ3k_Ev9Vq0mF1W3V-4KKXhqqkLjElmf6USsz961j55_4se2HYGdmuXSgNHr6zBz6ogbV5Axp-YbaEmv-GOlGn9fClkP5Qv-Xk_Cg3xYWIkSpknzRbjOLuCb0phSNPJbAip9GauwU2ea7U_FTpxtZI0UDYcBEHTiIv6l5wydmKOzrg</value>
      <webElementGuid>ba888a64-8263-436b-ac5a-adbd097c6a7d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cache-control</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>3610352c-04c4-4e07-b60b-5514e906c4dc</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ccf9cc48-15cc-4410-a14d-90449dd916a5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>8fe3e438-c71f-499b-82e0-94290b7a3702</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origin</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa</value>
      <webElementGuid>7c73ea16-8dac-455c-8166-3139c836045f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pragma</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>14324d63-b66d-484a-8f14-e8210f1295da</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referer</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa/authnticate/crm/requests/view/23dd4dd4-db84-4744-998d-5d2742985e40</value>
      <webElementGuid>74db5fcf-c40d-4ce1-91c3-0c528dc02023</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;110&quot;, &quot;Not A(Brand&quot;;v=&quot;24&quot;, &quot;Google Chrome&quot;;v=&quot;110&quot;</value>
      <webElementGuid>90f73606-e2da-4bfa-8d08-e38d0100e6b2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>a63df880-ca82-4632-803d-56afe200d60b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>128bd975-a95a-484f-9101-3ea23c13c392</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>29df7fca-9953-45df-abca-085731617de3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>b9bab944-d2a7-4b8c-a486-634b4d377e52</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>e6340482-63f5-4517-9175-eb0b2790bc80</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36</value>
      <webElementGuid>31490ef2-74b4-442c-9826-4b9e97247164</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://stage.saudiesports.sa/api/team-club/v1/requests/club-owner-request</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
