<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>filter request by request ID</name>
   <tag></tag>
   <elementGuidId>257b1831-44dd-466d-b794-bc47e140c1da</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;filters\&quot;: [\r\n        {\r\n            \&quot;columnName\&quot;: \&quot;name\&quot;,\r\n            \&quot;columnValue\&quot;: \&quot;${requestId}\&quot;,\r\n            \&quot;columnValues\&quot;: [],\r\n            \&quot;operator\&quot;: \&quot;equals\&quot;\r\n        }\r\n    ],\r\n    \&quot;pageNo\&quot;: 0,\r\n    \&quot;pageLength\&quot;: 10,\r\n    \&quot;sorting\&quot;: [\r\n        {\r\n            \&quot;sortName\&quot;: \&quot;createdAt\&quot;,\r\n            \&quot;sortType\&quot;: \&quot;DESC\&quot;,\r\n            \&quot;sortColumnType\&quot;: \&quot;date\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authority</name>
      <type>Main</type>
      <value>stage.saudiesports.sa</value>
      <webElementGuid>d15ddcbf-be1f-439e-adaa-0eea1f67d669</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>67ed0640-7ce5-4785-9e10-ce03ff713aeb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>9fc52e8e-8e85-4679-99ad-d71576325bb8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5dzdmVHQzQTc3QmFLWjVTMlp4czNBeEZybEZ2a3JVNG1fMkI3WjQwX2s0In0.eyJleHAiOjE2Nzc1OTQzNTQsImlhdCI6MTY3NzU5MDc1NCwiYXV0aF90aW1lIjoxNjc3NTkwNzUyLCJqdGkiOiI2OTFhZTMwYy1mMGQ5LTQ2MjktYWFkZi03ZDViMGY4YWJkYTAiLCJpc3MiOiJodHRwczovL3N0YWdlLnNhdWRpZXNwb3J0cy5zYS9hdXRoL3JlYWxtcy9jdXN0X2VzcG9ydHMuY29tIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjU3ZmJjNWQ4LWZkMzUtNGY3MC05MTA4LTk0Mjc5Nzc3MmUxOCIsInR5cCI6IkJlYXJlciIsImF6cCI6IldFQiIsIm5vbmNlIjoiNDI4NWU5NWYtZTIyYy00NmQzLTk0YTktZDIwNjZlMGE1ZWY3Iiwic2Vzc2lvbl9zdGF0ZSI6IjhhYTlmMDUzLTlmMDItNGZlNC05NGY5LThhNzZlNjVhNDI4ZSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1jdXN0X2VzcG9ydHMuY29tIiwiQ19VUF9WX08iLCJDX1JfVkFTX08iLCJDX1VfQkxfTyIsIkNfUl9WQUxfTyIsIkNfVV9SU01fTyIsIkNfUl9TRF9PIiwiQ19PX0VfTyIsIkNfVVBfRF9PIiwiQ19VUF9FX08iLCJDX1VQX0FfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19VX1ZfTyIsIkNfVV9FX08iLCJDX09fVl9PIiwiQ19VX0RfTyIsIkNfUlNfRV9PIiwiQ19VX1VCTF9PIiwiRVNQT1JUIiwiQ19VX0VYUF9PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX1VfQV9PIiwiQ19SX1JBU19PIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjhhYTlmMDUzLTlmMDItNGZlNC05NGY5LThhNzZlNjVhNDI4ZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW5AZXNwb3J0cy5zYSIsImdpdmVuX25hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwibG9jYWxlIjoiZW4iLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZmFtaWx5X25hbWUiOiIiLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYWRtaW5AZXNwb3J0cy5zYSIsImNpZCI6IjFfU1RDU19DVVNUIn0.ZCwu76ewqSMaBtQFi1QJNtDkw-ZUVTOPevcoOz47iv6l6Phk08ogqQBc8SgJkk0miez_YizENB_ztPDtbGU5_8IQVrlnC7PoRJ_bPkVMP2ria2TwiWqgx5JowJFa8wDjJsuHawxmUS6dGT14925L8LdSvS2L86idIh_ahaFsdJ3k_Ev9Vq0mF1W3V-4KKXhqqkLjElmf6USsz961j55_4se2HYGdmuXSgNHr6zBz6ogbV5Axp-YbaEmv-GOlGn9fClkP5Qv-Xk_Cg3xYWIkSpknzRbjOLuCb0phSNPJbAip9GauwU2ea7U_FTpxtZI0UDYcBEHTiIv6l5wydmKOzrg</value>
      <webElementGuid>9375ef55-1fc8-42e2-8fa3-0740c4a42105</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cache-control</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>6e867590-aa29-4cf6-8850-c2d3887cb01c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>db8bf77e-fe73-4303-82e6-a8c58d0bd431</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>784b459d-b80b-4c82-ab69-a07c99ce3a3c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origin</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa</value>
      <webElementGuid>4c4c1298-13b6-409a-9e29-4b02a5a2d0d8</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pragma</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>7a98f220-c267-499a-8672-f58651d598d9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referer</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa/authnticate/crm/requests/view/23dd4dd4-db84-4744-998d-5d2742985e40</value>
      <webElementGuid>0064cd59-0258-4d79-a431-701b968bd7d6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;110&quot;, &quot;Not A(Brand&quot;;v=&quot;24&quot;, &quot;Google Chrome&quot;;v=&quot;110&quot;</value>
      <webElementGuid>88aeafcb-c0a6-484e-b564-79eebdd10184</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>16fb47e0-25ec-47e6-99f9-49e908abdf0c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>5777584c-bd53-425c-908d-71bcb0d6214f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>af5031d6-2cf3-4ead-a983-5aa3384ec5e7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>d2bc4772-9097-4063-8cb0-fc067ab62bfd</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>209a29ef-f7eb-4658-9453-7f9d317b59a9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36</value>
      <webElementGuid>303dbd72-8211-4ee4-aa8d-7dce4ddc6dfe</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/requests/club-owner-request</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.requestId</defaultValue>
      <description></description>
      <id>25b124d6-801f-4200-a9e4-9babd5eb1ca7</id>
      <masked>false</masked>
      <name>requestId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
