<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Postman Request</name>
   <tag></tag>
   <elementGuidId>665bd0dc-ce37-4421-b7e8-4dbda1a8f366</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;filters\&quot;: [\r\n        {\r\n            \&quot;columnName\&quot;: \&quot;name\&quot;,\r\n            \&quot;columnValue\&quot;: null,\r\n            \&quot;columnValues\&quot;: [],\r\n            \&quot;operator\&quot;: \&quot;equals\&quot;\r\n        }\r\n    ],\r\n    \&quot;pageNo\&quot;: 0,\r\n    \&quot;pageLength\&quot;: 10,\r\n    \&quot;sorting\&quot;: [\r\n        {\r\n            \&quot;sortName\&quot;: \&quot;createdAt\&quot;,\r\n            \&quot;sortType\&quot;: \&quot;DESC\&quot;,\r\n            \&quot;sortColumnType\&quot;: \&quot;date\&quot;\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authority</name>
      <type>Main</type>
      <value>stage.saudiesports.sa</value>
      <webElementGuid>95d2e876-8b3c-4098-bc6f-a16570544d64</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>c8064a76-9440-48ff-9e0d-54419612891b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>e96887b2-227e-4c06-9fbd-a24d20b5136b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ5dzdmVHQzQTc3QmFLWjVTMlp4czNBeEZybEZ2a3JVNG1fMkI3WjQwX2s0In0.eyJleHAiOjE2Nzc1ODY4MTUsImlhdCI6MTY3NzU4MzIxNSwiYXV0aF90aW1lIjoxNjc3NTgzMjEzLCJqdGkiOiIxYTcwYWU0OC05OWI1LTRmZWUtODhkNC1lNmIxZjI4ZTVjYmMiLCJpc3MiOiJodHRwczovL3N0YWdlLnNhdWRpZXNwb3J0cy5zYS9hdXRoL3JlYWxtcy9jdXN0X2VzcG9ydHMuY29tIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjU3ZmJjNWQ4LWZkMzUtNGY3MC05MTA4LTk0Mjc5Nzc3MmUxOCIsInR5cCI6IkJlYXJlciIsImF6cCI6IldFQiIsIm5vbmNlIjoiNzdiNjkwZTItN2E4OC00ZjU1LTk4NDgtM2I3NGQwMGI0ZDYzIiwic2Vzc2lvbl9zdGF0ZSI6ImQxYjFjYTIwLThmOTktNGJkZS1hNGFjLTM3OWIwMzg0MmNlYSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1jdXN0X2VzcG9ydHMuY29tIiwiQ19VUF9WX08iLCJDX1JfVkFTX08iLCJDX1VfQkxfTyIsIkNfUl9WQUxfTyIsIkNfVV9SU01fTyIsIkNfUl9TRF9PIiwiQ19PX0VfTyIsIkNfVVBfRF9PIiwiQ19VUF9FX08iLCJDX1VQX0FfTyIsIm9mZmxpbmVfYWNjZXNzIiwiQ19VX1ZfTyIsIkNfVV9FX08iLCJDX09fVl9PIiwiQ19VX0RfTyIsIkNfUlNfRV9PIiwiQ19VX1VCTF9PIiwiRVNQT1JUIiwiQ19VX0VYUF9PIiwidW1hX2F1dGhvcml6YXRpb24iLCJDX1VfQV9PIiwiQ19SX1JBU19PIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6ImQxYjFjYTIwLThmOTktNGJkZS1hNGFjLTM3OWIwMzg0MmNlYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWRtaW5AZXNwb3J0cy5zYSIsImdpdmVuX25hbWUiOiJhZG1pbiB0ZXN0IGNoYW5nZSBuYW1lIiwibG9jYWxlIjoiZW4iLCJyaWQiOiJjdXN0X2VzcG9ydHMuY29tIiwiZmFtaWx5X25hbWUiOiIiLCJrZXkiOiJjdXN0X2VzcG9ydHMuY29tX0tFWSIsImVtYWlsIjoiYWRtaW5AZXNwb3J0cy5zYSIsImNpZCI6IjFfU1RDU19DVVNUIn0.KU_rvlW3SLE6ClgrNDBrCFn4L60X6dw3XDZUq4YSApKyD1pN3rh9op9uN08ec40TVyta1lMLh2P6TGdzmUI4mtoVPfB5UiCwa2RADnURcGfIVuPBPgqivAAnCHRGTCO_L-5PvqtdTivEH3bUFHUxrpfF4MRtEjd3HTohfb94Do6Hzql3bWO5sMstvYW3ebtIb7NYHZbi_ib6SB5ENH8fK-x8Coi8dXk_ZUE8I0q1r_u50EAiJPutN_284iSz3p-lU6hiA6xK38qRzx2Llqh8p_uQ4y9QroL3tuR-Nln3CtUeOHKeBLeKoeakh1tUg12es47ET_92KI8uYJGn14UQ8Q</value>
      <webElementGuid>593ef8cd-0d67-4f65-a60f-da2f851820a6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cache-control</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>4a74e482-89d2-40cb-bf04-1189d4d55df6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ddde0806-3855-4ebc-a89d-637d94e18a2a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>de5d46f1-c6a9-48b6-ac0f-5b933258f1f2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>origin</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa</value>
      <webElementGuid>16f1bded-9899-482c-ba5c-45fe9dab84e5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pragma</name>
      <type>Main</type>
      <value>no-cache</value>
      <webElementGuid>60271c48-e0e1-470d-9bf1-b6d3df6dfcb2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referer</name>
      <type>Main</type>
      <value>https://stage.saudiesports.sa/authnticate/crm/requests</value>
      <webElementGuid>c336595c-e350-45d9-a890-ea00111f252f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Chromium&quot;;v=&quot;110&quot;, &quot;Not A(Brand&quot;;v=&quot;24&quot;, &quot;Google Chrome&quot;;v=&quot;110&quot;</value>
      <webElementGuid>2056f25c-0f72-4f4b-ab40-9cb5fef99f3a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>2896fe0a-5b58-4b5d-8740-70b418312c0f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>06475465-711a-4542-bbdb-c9b724baa392</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>bb1b74ab-0e8e-41da-aafd-68819f7f2b2f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>22a3fb75-9603-4d9e-800e-8a5b7d595f96</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-fetch-site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>ea774d4a-7fbf-4d34-bea0-e03ec8931ced</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>user-agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36</value>
      <webElementGuid>afe0dea6-4b8b-4f32-aa04-c72a599ce6ec</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://stage.saudiesports.sa/api/team-club/v1/requests/club-owner-request</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
