<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>ReassignCRMRequest</name>
   <tag></tag>
   <elementGuidId>97d83019-d782-459a-bc4f-98368930786b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\&quot;userId\&quot;:\&quot;dc4b74f9-f698-4cc8-be30-df163df31bc0\&quot;}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>f1a18ed8-df63-40b3-b3e8-faf04e0e4739</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept-Language</name>
      <type>Main</type>
      <value>en-GB,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6</value>
      <webElementGuid>c83fe486-ddd1-45a2-8e72-4ab4d7745a9e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJxLVFhRE5IVFFiN29WMGsydlhHY041N3NpbWpCVnhpT1pfeXFPOGhfbFVrIn0.eyJleHAiOjE3MDczOTg4NzIsImlhdCI6MTcwNzM5NTI3MiwiYXV0aF90aW1lIjoxNzA3Mzk0ODU5LCJqdGkiOiI1ZTY5OTJjOC04YWQwLTQ4OGYtOTZlYS01ZDM4YmIzZWM2NWQiLCJpc3MiOiJodHRwczovL3VhdC5zYXVkaWVzcG9ydHMuc2EvYXV0aC9yZWFsbXMvY3VzdF9lc3BvcnRzLmNvbSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkYzRiNzRmOS1mNjk4LTRjYzgtYmUzMC1kZjE2M2RmMzFiYzAiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJXRUIiLCJub25jZSI6IjlkMTQ0ODA5LWQ5ZDAtNGQxYy1iMzE5LWFkZDBmNzIyMDY4MSIsInNlc3Npb25fc3RhdGUiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkNfVVBfVl9PIiwiQ19SX1ZBU19PIiwiQ19UX1VBUl9PIiwiQ19VX0JMX08iLCJDX0NMX01QX08iLCJDX1RfVUFMX08iLCJDX1JfU0RfTyIsIkNfT19FX08iLCJDX0VWX0xfTyIsIkNfVVBfRF9PIiwiQ19UQ19FX08iLCJDX1BBUl9DQU5fTyIsIkNfQ0xfRU1ZX08iLCJDX0NSUV9FX08iLCJDX1RfVl9PIiwiQ19QQVJfRV9MX08iLCJDX1VfRF9PIiwiQ19DTF9WTVlfTyIsInVtYV9hdXRob3JpemF0aW9uIiwiQ19QQVJfRV9PIiwiQ19VX1JTTV9PIiwiQ19UX01UQV9PIiwiQ19FVlJfRV9PIiwiQ19NRV9CTF9PIiwiQ19UX0RTX08iLCJDX0NMX01BX08iLCJDX1RXX0VfTyIsIkNfTUVfVU5CX08iLCJDX01FX0RTX08iLCJDX1ZfQVNfTyIsImRlZmF1bHQtcm9sZXMtY3VzdF9lc3BvcnRzLmNvbSIsIkNfQUxfRVhQX08iLCJDX0NMX1ZfTyIsIkNfVF9BX08iLCJDX0VWX0VfTyIsIkNfUl9WQUxfTyIsIkNfVF9FX08iLCJDX1RfQVJfTyIsIkNfQ0xfRUFMX08iLCJDX0NMX0VYUF9PIiwiQ19UX0VBTF9PIiwiQ19VUF9FX08iLCJvZmZsaW5lX2FjY2VzcyIsIkNfVVBfQV9PIiwiQ19DTF9BU19PIiwiQ19VX0VfTyIsIkNfT19WX08iLCJDX1JTX0VfTyIsIkNfVV9VQkxfTyIsIkVTUE9SVCIsIkNfTUVfRVhQX08iLCJDX0NMX1VCTF9PIiwiQ19VX0VYUF9PIiwiQ19VX0FfTyIsIkNfUl9SQVNfTyIsIkNfVF9SQ19PIiwiQ19QQVJfTF9PIiwiQ19UX0VYUF9PIiwiQ19QQVJfSVNVX08iLCJDX0NMX0JMX08iLCJDX01FX0VBUF9PIiwiQ19DTF9DQUxfTyIsIkNfTUVfVkVSX08iLCJDX1VfVl9PIiwiQ19NRV9NQV9PIiwiQ19BUkNfRV9PIiwiQ19NRV9WQUxfTyIsIkNfRVZfQ0FOX08iLCJDX0NMX0RTX08iLCJDX05SX0VfTyIsIkNfVF9BUkxfTyJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJmODVkNGViOS0wNDk5LTQxMjYtYjJiNC1hOTc2ZmI2MjdlNDgiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwidWxpZCI6ImY5NGUwMjUxLTYyZDEtNGFhNC1iYzU1LWM0MzM0ZDNmYTExNCIsIm5hbWUiOiJzdXBlciBhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Iis5NjY1NTQyNTQyMzIiLCJnaXZlbl9uYW1lIjoic3VwZXIgYWRtaW4iLCJsb2NhbGUiOiJlbiIsInJpZCI6ImN1c3RfZXNwb3J0cy5jb20iLCJmYW1pbHlfbmFtZSI6IiIsImtleSI6ImN1c3RfZXNwb3J0cy5jb21fS0VZIiwiZW1haWwiOiJhZG1pbkBzYXVkaWVzcG9ydHMuc2EiLCJjaWQiOiIxX1NUQ1NfQ1VTVCJ9.JIsKcP-hk4xHaLSAiPTiEAKSHM90GRuM_QrFdQBuzF7_dccDKcaH01YlULjlZG9VTwW_N4u2eFzpzoXMKICeKdylNR8mTHRm7bNDB_BcQxWS6xPSrC_jRpWblvnpYneOjhi9CZmuWBTKq3jmlpz9FRX8u0IXfZETLIJ_9ot1o2BLYyMjUdgQQRxbaTaouYhujxDqweMXELL8w_rOeDVTK5DcdnG3efmvgie_Oj-BJI1TZe6Vx5V9OTZOqwQhbHFk_pPbJerH3W5AN2M0fRmnKM9hFaomvUzO-IQfzsNGhHMxUCO93a6AapaoCI4h4Y5MmD5wx293btEAt6xEIYf88A</value>
      <webElementGuid>0500649b-7c05-4302-aca4-e6df687cb4f6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Connection</name>
      <type>Main</type>
      <value>keep-alive</value>
      <webElementGuid>203fa232-6fe3-4470-ad2f-cb922610bcb0</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0e4b8000-360a-478a-ae85-f2995b1cbc84</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Entity</name>
      <type>Main</type>
      <value>authnticate</value>
      <webElementGuid>d9bb87df-920d-43df-9f6f-3f93be8ca19e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Origin</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa</value>
      <webElementGuid>36c50fe9-3267-4a7a-a46c-dc45fc6e8d37</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Referer</name>
      <type>Main</type>
      <value>https://uat.saudiesports.sa/authnticate/crm/requests/view-contract-requests/bda69bd6-1ddf-427a-8620-fffa308a0688</value>
      <webElementGuid>915365ec-0e66-4e56-b525-fa6551f7e603</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Dest</name>
      <type>Main</type>
      <value>empty</value>
      <webElementGuid>292d649f-21c7-484a-aab5-12cb4276fa27</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Mode</name>
      <type>Main</type>
      <value>cors</value>
      <webElementGuid>9d47f6e0-e2e1-475b-8129-7f8e0ba7e468</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Sec-Fetch-Site</name>
      <type>Main</type>
      <value>same-origin</value>
      <webElementGuid>e9c3002b-731e-4d85-a2ec-ff0cea654137</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>User-Agent</name>
      <type>Main</type>
      <value>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36</value>
      <webElementGuid>d4c1ce01-1933-4937-a682-42fe5f29df89</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua</name>
      <type>Main</type>
      <value>&quot;Not A(Brand&quot;;v=&quot;99&quot;, &quot;Google Chrome&quot;;v=&quot;121&quot;, &quot;Chromium&quot;;v=&quot;121&quot;</value>
      <webElementGuid>d09f90cc-f707-424d-960c-0d0e6183157f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-mobile</name>
      <type>Main</type>
      <value>?0</value>
      <webElementGuid>4ff6ec13-d88e-47c1-aed4-ea23e2321236</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sec-ch-ua-platform</name>
      <type>Main</type>
      <value>&quot;Windows&quot;</value>
      <webElementGuid>61ae5baf-4be6-4e79-963d-7f362f2cb440</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.4.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PATCH</restRequestMethod>
   <restUrl>https://uat.saudiesports.sa/api/team-club/v1/assigned_request/bda69bd6-1ddf-427a-8620-fffa308a0688/reassign</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
